### ISSUE TITLE
freeorion segfaults after the server quits

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#1092]
Also somehow CMAKE_BUILD_TYPE=Debug doesn't seem to produce symbols anymore:
```
(gdb) bt
#0  0x0000000bcac3e5a2 in ?? ()
#1  0x0000039f60000dd0 in ?? ()
#2  0x0000039f66381be0 in ?? ()
#3  0x0000039f66381c00 in ?? ()
#4  0x9f8a03f2ecda1200 in ?? ()
#5  0x0000039f66381cb0 in ?? ()
#6  0x0000000000000001 in ?? ()
#7  0x0000039f66381c00 in ?? ()
#8  0x0000000bcac3e928 in ?? ()
#9  0x0000039f66381c00 in ?? ()
#10 0x0000039f60000dc0 in ?? ()
#11 0x0000039f66381ce0 in ?? ()
#12 0x9f8a03f2ecda1200 in ?? ()
#13 0x0000000000000001 in ?? ()
#14 0x0000000000000001 in ?? ()
#15 0x0000039f66381d20 in ?? ()
#16 0x0000000bcad8188b in ?? ()
#17 0x0000039f60000dc0 in ?? ()
#18 0x000003ec2a4b4038 in ?? ()
#19 0x0000000bd1c95c80 in ?? ()
#20 0x0000000bd1c95c80 in ?? ()
#21 0x0000039f66381d80 in ?? ()
#22 0x0000000bcad81e20 in ?? ()
#23 0x0000039f60001180 in ?? ()
#24 0x0000000bce0fc8d0 in ?? ()
#25 0x0000000bcad8209a in ?? ()
#26 0x0000000000002d0d in ?? ()
#27 0x0000000bce0fc900 in ?? ()
#28 0x9f8a03f2ecda1200 in ?? ()
#29 0x0000000bce0fc8d0 in ?? ()
#30 0x0000039f66381c90 in ?? ()
#31 0x0000000000000002 in ?? ()
#32 0x0000000bcbcd9478 in ?? ()
#33 0x0000039f60000ab0 in ?? ()
#34 0x0000000000000000 in ?? ()
```

**Comment by l29ah** [comment]
Nope, symbols are there but still the core dump contains this shit instead.

**Comment by LGM-Doyle** [comment]
I could not replicate this bug.

I need a more detailed set of steps that reliably replicates the issue, in order to fix it.

What OS are you using?
Are you playing multiplayer?
How are you starting the server?
How are you exiting the server?
Are you exiting the client?

Thanks for taking the time to submit the bug report.  I hope that you can expand it so that it can be replicated and fixed.

**Comment by o01eg** [comment]
@l29ah You can open dump in gdb and load there debug symbols.

**Comment by l29ah** [comment]
I've lost the dump already. I'll try to replicate the bug on master.
