### ISSUE TITLE
Crash in multiplayer lobby

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#1193]
```
#0  0x0000038209303b51 in boost::unordered::detail::table<boost::unordered::detail::set<std::allocator<std::_List_iterator<GG::ListBox::Row*> >, std::_List_iterator<GG::ListBox::Row*>, GG::ListBox::IteratorHash, std::equal_to<std::_List_iterator<GG::ListBox::Row*> > > >::begin (this=0x33ae82c428)
    at /usr/include/boost/unordered/detail/table.hpp:181
#1  0x0000038209301b4e in boost::unordered::unordered_set<std::_List_iterator<GG::ListBox::Row*>, GG::ListBox::IteratorHash, std::equal_to<std::_List_iterator<GG::ListBox::Row*> >, std::allocator<std::_List_iterator<GG::ListBox::Row*> > >::begin (this=0x33ae82c428) at /usr/include/boost/unordered/unordered_set.hpp:207
#2  0x00000382092faae6 in ModalListPicker::CurrentItem (this=0x33ae690b20)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/DropDownList.cpp:227
#3  0x00000382092fa5e1 in ModalListPicker::Run (this=0x33ae690b20)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/DropDownList.cpp:177
#4  0x00000382092fe8e0 in GG::DropDownList::LClick (this=0x33ae690560, pt=..., mod_keys=...)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/DropDownList.cpp:807
#5  0x00000033a9ebc4b1 in CUIDropDownList::LClick (this=0x33ae690560, pt=..., mod_keys=...)
    at /home/l29ah/projects/freeorion-teamsmac-debug/UI/CUIControls.cpp:841
#6  0x00000382095b00e0 in GG::Wnd::HandleEvent (this=0x33ae690560, event=...)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/Wnd.cpp:1093
#7  0x0000038209402648 in GG::GUIImpl::HandleMouseButtonRelease (this=0x33ab74f160, mouse_button=0, pos=..., 
    curr_ticks=1621779) at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/GUI.cpp:518
#8  0x0000038209406544 in GG::GUI::HandleGGEvent (this=0x39540a33668, event=GG::GUI::LRELEASE, 
    key=GG::GGK_UNKNOWN, key_code_point=0, mod_keys=..., pos=..., rel=..., text=0x0)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/GUI.cpp:1142
#9  0x000003820b7fe94c in GG::SDLGUI::HandleSystemEvents (this=0x39540a33668)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/SDL/SDLGUI.cpp:800
#10 0x00000033a9be112d in HumanClientApp::HandleSystemEvents (this=0x39540a32ac0)
    at /home/l29ah/projects/freeorion-teamsmac-debug/client/human/HumanClientApp.cpp:820
#11 0x000003820934fdb1 in GG::ModalEventPump::operator() (this=0x39540a32980)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/EventPump.cpp:113
#12 0x000003820b7fee0e in GG::SDLGUI::Run (this=0x39540a33668)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/SDL/SDLGUI.cpp:882
#13 0x00000382094061bd in GG::GUI::operator() (this=0x39540a33668)
---Type <return> to continue, or q <return> to quit---
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/GUI.cpp:1087
#14 0x000003820b7fd9dc in GG::SDLGUI::operator() (this=0x39540a33668)
    at /home/l29ah/projects/freeorion-teamsmac-debug/GG/src/SDL/SDLGUI.cpp:529
#15 0x00000033a9c86a47 in mainSetupAndRun ()
    at /home/l29ah/projects/freeorion-teamsmac-debug/client/human/chmain.cpp:284
#16 0x00000033a9c836a4 in main (argc=1, argv=0x39540a33948)
    at /home/l29ah/projects/freeorion-teamsmac-debug/client/human/chmain.cpp:101
```

**Comment by adrianbroher** [comment]
Not reproducible with the information given.
