### ISSUE TITLE
AI fails when taking over human empire

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1207]
save: http://dump.bitcheese.net/files/rixyjul/l_o_v.mps

Take Voker57 empire, set AI for O01eg empire, start game, boom! AI_4 no longer has connection to server.

Revision: f6e9c278963e2a4

**Comment by dbenage-cx** [comment]
AI_1.log errors:
```
AI : LoggingWrapper.cpp:23 : Chat Message to human: AI_Error: AI script error: "Fail to load aiState form saved game: "
AI : : : Traceback (most recent call last):
AI : : :   File "/opt/projects/freeorion/default/python/AI/FreeOrionAI.py", line 122, in resumeLoadedGame
AI : : :     foAIstate = pickle.loads(saved_state_string)
AI : : :   File "/usr/lib64/python2.7/pickle.py", line 1388, in loads
AI : : :     return Unpickler(file).load()
AI : : :   File "/usr/lib64/python2.7/pickle.py", line 864, in load
AI : : :     dispatch[key](self)
AI : : :   File "/usr/lib64/python2.7/pickle.py", line 886, in load_eof
AI : : :     raise EOFError
AI : : : EOFError

AI : LoggingWrapper.cpp:23 : Chat Message to human: AI_Error: AI script error in "generateOrders": "Unable to find key in unordered_map."
AI : : : Traceback (most recent call last):
AI : : :   File "/opt/projects/freeorion/default/python/AI/freeorion_tools/_freeorion_tools.py", line 95, in wrapper
AI : : :     return function(*args, **kw)
AI : : :   File "/opt/projects/freeorion/default/python/common/listeners.py", line 42, in wrapper
AI : : :     res = funct(*args)
AI : : :   File "/opt/projects/freeorion/default/python/AI/FreeOrionAI.py", line 240, in generateOrders
AI : : :     foAIstate.refresh()  # checks exploration border & clears roles/missions of missing fleets & updates fleet locs & threats
AI : : :   File "/opt/projects/freeorion/default/python/AI/AIstate.py", line 165, in refresh
AI : : :     newly_explored = ExplorationAI.update_explored_systems()
AI : : :   File "/opt/projects/freeorion/default/python/AI/ExplorationAI.py", line 245, in update_explored_systems
AI : : :     neighbors = list(universe.getImmediateNeighbors(sys_id, empire_id))
AI : : : IndexError: Unable to find key in unordered_map.
AI : AIClientApp.cpp:148 : AIClientApp failed due to error in python AI code for AI_1.  Exiting Soon. id = 2

```

freeoriond.log
```
Server : ServerFSM.cpp:1107 : (ServerFSM) PlayingGame.PlayerChat
Server : ServerNetworking.cpp:216 : Server received message from player id: 2 of type Player Chat and size 110
Server : ServerFSM.cpp:1107 : (ServerFSM) PlayingGame.PlayerChat
Server : ServerNetworking.cpp:216 : Server received message from player id: -1 of type Error and size 246
Server : ServerApp.cpp:382 : ServerApp::HandleMessage : Received an message with a sender ID (-1) that differs from the sending player connection ID: 2.  Ignoring.
Server : ServerNetworking.cpp:545 : ServerNetworking::DisconnectImpl : disconnecting player 2
Server : ServerFSM.cpp:222 : ServerFSM::HandleNonLobbyDisconnection : Lost connection to player #2, named "AI_1"; server terminating.
Server : ServerFSM.cpp:236 : ServerFSM::HandleNonLobbyDisconnection : All human players disconnected; server terminating.
```

For errors: AI_2.log only has the "Fail to load aiState" block.
Other AI logs have no errors.


Some discussion on previous (possibly related) issue: #781

**Comment by Cjkjvfnby** [comment]
I can look at it after 16 January. Feel free to ping me after this date.

**Comment by Cjkjvfnby** [comment]
I did not manage to test this with attached savegame.  This file does not present in load game dialog.

**Comment by Vezzra** [comment]
@Voker57, please report back should the issue persist even with @Cjkjvfnby's fix.

**Comment by Voker57** [comment]
There's a different error now, not sure if it's related https://ipfs.io/ipfs/QmSZ46X7Rp93oE9h6otdpzeTYC9bvoYjmiWcAdgGjvi7gM (freeorion.log)

**Comment by Cjkjvfnby** [comment]
Looks like check if empire is eliminated missed in more places around project.   Looks like it is not affect a game, to I expect nobody will fix them.

**Comment by Vezzra** [comment]
@Voker57, can you open a new issue for this new error?

**Comment by Voker57** [comment]
OK
