### ISSUE TITLE
Freeorion freeze on new turn.

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#1217]
### Environment

* **FreeOrion Version**: v0.4.6+ teamsmac [build 2017-01-11.ed51695]
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA
* **Fetched as** 
  * Compiled from source

### Description

The game freeze on new turn.
https://gist.githubusercontent.com/o01eg/a39824566fd8109ef10846b33e6ffe56/raw/0606d42a07daf67600c5c3b4d83aa2eda187d177/freeorion.log
```
(gdb) thread apply all bt

Thread 3 (Thread 0x7fffe730b700 (LWP 4295)):
#0  0x00007ffff7de21e8 in do_lookup_x () from /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7de2d7f in _dl_lookup_symbol_x () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7de7826 in _dl_fixup () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7dee8f3 in _dl_runtime_resolve_avx () from /lib64/ld-linux-x86-64.so.2
#4  0x00000000007db874 in ?? ()
#5  0x0000000000000005 in ?? ()
#6  0x0000000000f58c10 in ?? ()
#7  0x0000000002c58318 in ?? ()
#8  0x00000000004d2768 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, boost::_bi::bind_t<void, boost::_mfi::mf2<void, ClientNetworking, boost::system::error_code, unsigned long>, boost::_bi::list3<boost::_bi::value<ClientNetworking*>, boost::arg<1> (*)(), boost::arg<2> (*)()> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#9  0x00000000004ce86a in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#10 0x00000000004ce5c0 in boost::asio::detail::task_io_service::run(boost::system::error_code&) ()
#11 0x00000000004c746b in ClientNetworking::NetworkingThread() ()
#12 0x00007ffff3994215 in ?? () from /usr/lib64/libboost_thread.so.1.62.0
#13 0x00007ffff611a494 in start_thread () from /lib64/libpthread.so.0
#14 0x00007ffff248994d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fffe8baa700 (LWP 4276)):
#0  0x00007ffff248084d in poll () from /lib64/libc.so.6
#1  0x00007ffff17db321 in ?? () from /usr/lib64/libasound.so.2
#2  0x00007ffff17db56f in snd_pcm_wait () from /usr/lib64/libasound.so.2
#3  0x00007ffff666c092 in ?? () from /usr/lib64/libopenal.so.1
#4  0x00007ffff666429a in ?? () from /usr/lib64/libopenal.so.1
#5  0x00007ffff611a494 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffff248994d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7f8a7c0 (LWP 4271)):
#0  0x00007ffff2cdab67 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/libstdc++.so.6
#1  0x00000000005e6340 in FleetUIManager::CullEmptyWnds() ()
#2  0x00000000006520c7 in MapWnd::Render() ()
#3  0x00007ffff4d5f40c in GG::GUI::RenderWindow(GG::Wnd*) () from /mnt/new/o01eg/games/freeorion-teamsmac/lib64/freeorion/libGiGi.so
#4  0x00007ffff4d5ff05 in GG::GUI::Render() () from /mnt/new/o01eg/games/freeorion-teamsmac/lib64/freeorion/libGiGi.so
#5  0x00007ffff4d285a0 in GG::EventPumpBase::LoopBody(GG::GUI*, GG::EventPumpState&, bool, bool) ()
   from /mnt/new/o01eg/games/freeorion-teamsmac/lib64/freeorion/libGiGi.so
#6  0x00007ffff4d288b2 in GG::ModalEventPump::operator()() () from /mnt/new/o01eg/games/freeorion-teamsmac/lib64/freeorion/libGiGi.so
#7  0x00007ffff6dba2b6 in GG::SDLGUI::Run() () from /mnt/new/o01eg/games/freeorion-teamsmac/lib64/freeorion/libGiGiSDL.so
#8  0x000000000048b3da in mainSetupAndRun() ()
#9  0x0000000000452b82 in main ()
```

**Comment by geoffthemedio** [comment]
Happened once, or happens every time you try to end the turn?

What does "freeze" mean?

**Comment by o01eg** [comment]
It happened sometimes when turn ends. Mouse pointer and even music thread stops.

**Comment by adrianbroher** [comment]
ed51695 is not a valid git hash in the repository. Ask @V-ktor for support.

**Comment by o01eg** [comment]
It based on f3beec012e25883983e7fbb7b7eb52393c686115 and there no big changes in client code.

**Comment by Vezzra** [comment]
@o01eg, even so, please try to reproduce the issue with a build based on a commit in the official repo and then refer to that commit in your bug report, not one in your personal fork. Makes things easier for us, and also makes sure the issue is indeed with our code, and not with yours (regardless how minor your adjustments may be).

**Comment by schumaml** [comment]
I did experience these symptoms until I switched to binary save files.

**Comment by Vezzra** [comment]
@o01eg, do you still experience this issue with recent test builds?

**Comment by o01eg** [comment]
No, I suppose it either was introduced in content changes or was fixed somehow.
