### ISSUE TITLE
AI still fails when taking over human empire

### ISSUE THREAD

**Issue by Voker57** [freeorion/freeorion#1285]
Save file: http://dump.bitcheese.net/files/muvukez/l_v_n_o.mps

I picked Voker57, set AI for L29Ah.

AI log: http://dump.bitcheese.net/files/nexolal/AI_4.log 

```
v0.4.6+ teamsmac [build 2017-02-05.7605a7f] CMake
...
2017-02-06 00:22:27.157337 [error] AI : : : Traceback (most recent call last):
2017-02-06 00:22:27.157368 [error] AI : : :   File "/opt/freeorion/share/freeorion/default/python/AI/freeorion_tools/_freeorion_tools.py", line 95, in wrapper
2017-02-06 00:22:27.157408 [error] AI : : :     return function(*args, **kw)
2017-02-06 00:22:27.157425 [error] AI : : :   File "/opt/freeorion/share/freeorion/default/python/AI/FreeOrionAI.py", line 139, in prepareForSave
2017-02-06 00:22:27.157457 [error] AI : : :     dump_string = pickle.dumps(foAIstate)
2017-02-06 00:22:27.157470 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
2017-02-06 00:22:27.157581 [error] AI : : :     Pickler(file, protocol).dump(obj)
2017-02-06 00:22:27.157595 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 224, in dump
2017-02-06 00:22:27.157628 [error] AI : : :     self.save(obj)
2017-02-06 00:22:27.157640 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 331, in save
2017-02-06 00:22:27.157677 [error] AI : : :     self.save_reduce(obj=obj, *rv)
2017-02-06 00:22:27.157690 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
2017-02-06 00:22:27.157736 [error] AI : : :     save(state)
2017-02-06 00:22:27.157748 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 286, in save
2017-02-06 00:22:27.157781 [error] AI : : :     f(self, obj) # Call unbound method with explicit self
2017-02-06 00:22:27.157793 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
2017-02-06 00:22:27.157851 [error] AI : : :     self._batch_setitems(obj.iteritems())
2017-02-06 00:22:27.157863 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
2017-02-06 00:22:27.157925 [error] AI : : :     save(v)
2017-02-06 00:22:27.157936 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 331, in save
2017-02-06 00:22:27.157972 [error] AI : : :     self.save_reduce(obj=obj, *rv)
2017-02-06 00:22:27.157984 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
2017-02-06 00:22:27.158030 [error] AI : : :     save(state)
2017-02-06 00:22:27.158046 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 286, in save
2017-02-06 00:22:27.158081 [error] AI : : :     f(self, obj) # Call unbound method with explicit self
2017-02-06 00:22:27.158093 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
2017-02-06 00:22:27.158154 [error] AI : : :     self._batch_setitems(obj.iteritems())
2017-02-06 00:22:27.158165 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
2017-02-06 00:22:27.158223 [error] AI : : :     save(v)
2017-02-06 00:22:27.158235 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 286, in save
2017-02-06 00:22:27.158271 [error] AI : : :     f(self, obj) # Call unbound method with explicit self
2017-02-06 00:22:27.158283 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 606, in save_list
2017-02-06 00:22:27.158338 [error] AI : : :     self._batch_appends(iter(obj))
2017-02-06 00:22:27.158350 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 621, in _batch_appends
2017-02-06 00:22:27.158407 [error] AI : : :     save(x)
2017-02-06 00:22:27.158419 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 331, in save
2017-02-06 00:22:27.158458 [error] AI : : :     self.save_reduce(obj=obj, *rv)
2017-02-06 00:22:27.158469 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
2017-02-06 00:22:27.158513 [error] AI : : :     save(state)
2017-02-06 00:22:27.158525 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 286, in save
2017-02-06 00:22:27.158559 [error] AI : : :     f(self, obj) # Call unbound method with explicit self
2017-02-06 00:22:27.158570 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
2017-02-06 00:22:27.158628 [error] AI : : :     self._batch_setitems(obj.iteritems())
2017-02-06 00:22:27.158640 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
2017-02-06 00:22:27.158699 [error] AI : : :     save(v)
2017-02-06 00:22:27.158712 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 331, in save
2017-02-06 00:22:27.158748 [error] AI : : :     self.save_reduce(obj=obj, *rv)
2017-02-06 00:22:27.158760 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 401, in save_reduce
2017-02-06 00:22:27.158801 [error] AI : : :     save(args)
2017-02-06 00:22:27.158813 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 286, in save
2017-02-06 00:22:27.158847 [error] AI : : :     f(self, obj) # Call unbound method with explicit self
2017-02-06 00:22:27.158859 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 568, in save_tuple
2017-02-06 00:22:27.158913 [error] AI : : :     save(element)
2017-02-06 00:22:27.158925 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 286, in save
2017-02-06 00:22:27.158959 [error] AI : : :     f(self, obj) # Call unbound method with explicit self
2017-02-06 00:22:27.158971 [error] AI : : :   File "/usr/lib/python2.7/pickle.py", line 754, in save_global
2017-02-06 00:22:27.159034 [error] AI : : :     (obj, module, name))
2017-02-06 00:22:27.159052 [error] AI : : : pickle.PicklingError: Can't pickle <type 'Boost.Python.enum'>: it's not found as Boost.Python.enum
2017-02-06 00:22:27.159077 [error] AI : AIClientApp.cpp:188 : AIClientApp failed due to error in python AI code for AI_4.  Exiting Soon. id = 6
```

**Comment by geoffthemedio** [comment]
You might be able to play that save by disabling autosave. Doubt that manual saves would work either, though.

**Comment by Cjkjvfnby** [comment]
IMHO it is better to reopen existing ticket then create "sill" one.

PS. I added log error part and build version to description.

**Comment by Cjkjvfnby** [comment]
Bad news that my windows version does not want to see this save.  I click multiplayer - host - load.  I see some old mps files (This files were provided by Voker57  `save-20160727_002645.mps`) but don't see this.

**Comment by Cjkjvfnby** [comment]
Check for `empire.eliminated` is present before this fail.  Looks like wrong argument was stored in save object.

@Voker57 you can just wrap this line to `try: ... catch exception: pass` block to work around this issue.

**Comment by geoffthemedio** [comment]
As with https://github.com/freeorion/freeorion/issues/1280 it appears to be a binary save file.

**Comment by Voker57** [comment]
I don't think I can provide XML format save since I need to save game for this, and saving game fails.

**Comment by Vezzra** [comment]
@Voker57, does the AI *always* fail to take over a human empire, or does that just happen sporadically?

**Comment by Cjkjvfnby** [comment]
> I don't think I can provide XML format save since I need to save game for this, and saving game fails.

I am confused, how did you managed to get this save?

Which platform it is?

**Comment by dbenage-cx** [comment]
@Cjkjvfnby Some empires were populated with human clients previously.
Attempting to load the game by setting all to AI (except 1 player) results in this issue.

An alternative may be to hotseat with multiple clients on the same machine.  Not recommended for normal use yet due to (at least) log file conflicts for the human client, but useful in a case like this.

**Comment by Cjkjvfnby** [comment]
I made function that print AI content to log.   Instruction how to run it is in PR(dont forget to deploy it) . May be its output will help me to understand issue reasons. 

https://github.com/Cjkjvfnby/freeorion/pull/18

**Comment by Voker57** [comment]
Save file in XML format: http://dump.bitcheese.net/files/wynolas/failing.mps
Reproduce: start MP game, set yourself to Voker57 empire, give one AI nj empire, end turn.

AI deep print log: https://gist.github.com/Voker57/4b6592688f6c84f5dec887932638881e

Reproduced on 90d8f4d9dcf4bc2adaf615d3bb2ca8c

**Comment by Voker57** [comment]
Bug is still present in some (?) situations

Save: http://dump.bitcheese.net/files/votejid/l_v_n_o_s.mps

Take empire Voker57, add one AI and let it pick its empire.

End turn 2 times.

AI log: http://dump.bitcheese.net/files/mijoser/AI_1.log

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/tree/AbortAIWithoutEmpire

Adds some checks that avoid AI crash chat messages, though doesn't solve the issue of why the single AI doesn't get a valid empire.

**Comment by Vezzra** [comment]
@Voker57, does the issue still exist in recent test builds?

**Comment by Voker57** [comment]
@Vezzra yes, still reproducible

**Comment by Vezzra** [comment]
Ok, needs to stay open then. Thanks for reporting back!

**Comment by Morlic-fo** [comment]
@Voker57:
Can you check if #1888 fixes the issue?

**Comment by Vezzra** [comment]
Ok, I'm taking the optimistic approach here and assume #1888 solved the issue, so tagging this as resolved. @Voker57, if the issue persists, please report back and we will reopen this.
