### ISSUE TITLE
Heap-buffer-overflow in creating universe in the second game session.

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#1732]
### Environment

* **FreeOrion Version**: 5f7fd1689d8a92c35af801e80c49ca3b97e4a073
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: NVIDIA GeForce 750 Ti
* **Fetched as** 
  * Compiled from source

### Description
The server runs on the same OS. After some turns in the first game session client was disconnected and then reconnected. While starting next game server gets heap-buffer-overflow.

```
==2372==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61100034dc48 at pc 0x7f7ef486290e bp 0x7fffffff8ea0 sp 0x7fffffff8e90
READ of size 2 at 0x61100034dc48 thread T0
    #0 0x7f7ef486290d in Pathfinder::PathfinderImpl::WithinJumpsCacheHit(std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&) const /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:1025
    #1 0x7f7ef487747e in void boost::_mfi::cmf4<void, Pathfinder::PathfinderImpl, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&>::call<Pathfinder::PathfinderImpl const* const, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> > >(Pathfinder::PathfinderImpl const* const&, void const*, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*&, unsigned long&, unsigned long&, std::vector<short, std::allocator<short> >&) const /usr/include/boost/bind/mem_fn_template.hpp:561
    #2 0x7f7ef487747e in void boost::_mfi::cmf4<void, Pathfinder::PathfinderImpl, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&>::operator()<Pathfinder::PathfinderImpl const*>(Pathfinder::PathfinderImpl const* const&, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&) const /usr/include/boost/bind/mem_fn_template.hpp:571
    #3 0x7f7ef487747e in void boost::_bi::list5<boost::_bi::value<Pathfinder::PathfinderImpl const*>, boost::_bi::value<std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*>, boost::_bi::value<unsigned long>, boost::arg<1>, boost::arg<2> >::operator()<boost::_mfi::cmf4<void, Pathfinder::PathfinderImpl, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&>, boost::_bi::rrlist2<unsigned long&, std::vector<short, std::allocator<short> >&> >(boost::_bi::type<void>, boost::_mfi::cmf4<void, Pathfinder::PathfinderImpl, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&>&, boost::_bi::rrlist2<unsigned long&, std::vector<short, std::allocator<short> >&>&, int) /usr/include/boost/bind/bind.hpp:531
    #4 0x7f7ef487747e in void boost::_bi::bind_t<void, boost::_mfi::cmf4<void, Pathfinder::PathfinderImpl, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&>, boost::_bi::list5<boost::_bi::value<Pathfinder::PathfinderImpl const*>, boost::_bi::value<std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*>, boost::_bi::value<unsigned long>, boost::arg<1>, boost::arg<2> > >::operator()<unsigned long&, std::vector<short, std::allocator<short> >&>(unsigned long&, std::vector<short, std::allocator<short> >&) /usr/include/boost/bind/bind.hpp:1318
    #5 0x7f7ef487747e in boost::detail::function::void_function_obj_invoker2<boost::_bi::bind_t<void, boost::_mfi::cmf4<void, Pathfinder::PathfinderImpl, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&>, boost::_bi::list5<boost::_bi::value<Pathfinder::PathfinderImpl const*>, boost::_bi::value<std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*>, boost::_bi::value<unsigned long>, boost::arg<1>, boost::arg<2> > >, void, unsigned long&, std::vector<short, std::allocator<short> >&>::invoke(boost::detail::function::function_buffer&, unsigned long&, std::vector<short, std::allocator<short> >&) /usr/include/boost/function/function_template.hpp:159
    #6 0x7f7ef48700b0 in boost::function2<void, unsigned long&, std::vector<short, std::allocator<short> >&>::operator()(unsigned long&, std::vector<short, std::allocator<short> >&) const /usr/include/boost/function/function_template.hpp:771
    #7 0x7f7ef485be35 in examine_row /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:203
    #8 0x7f7ef486313e in Pathfinder::PathfinderImpl::WithinJumps(unsigned long, std::vector<int, std::allocator<int> > const&) const /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:1056
    #9 0x7f7ef48635ad in Pathfinder::WithinJumps(unsigned long, std::vector<int, std::allocator<int> > const&) const /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:1032
    #10 0x20000019c437 in SystemsWithinJumps /mnt/another/srcs/GIT/freeorion/python/server/ServerWrapper.cpp:971
    #11 0x2000001b2ba1 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<boost::python::list (*)(unsigned long, boost::python::list), boost::python::default_call_policies, boost::mpl::vector3<boost::python::list, unsigned long, boost::python::list> > >::operator()(_object*, _object*) (/mnt/new/o01eg/games/freeorion-debug/bin/freeoriond+0x2000001b2ba1)
    #12 0x7f7ef309332c in boost::python::objects::function::call(_object*, _object*) const (/usr/lib64/libboost_python-2.7.so.1.62.0+0x2b32c)
    #13 0x7f7ef30934f7  (/usr/lib64/libboost_python-2.7.so.1.62.0+0x2b4f7)
    #14 0x7f7ef3099f22 in boost::python::handle_exception_impl(boost::function0<void>) (/usr/lib64/libboost_python-2.7.so.1.62.0+0x31f22)
    #15 0x7f7ef3090538  (/usr/lib64/libboost_python-2.7.so.1.62.0+0x28538)
    #16 0x7f7ef32fed43 in PyObject_Call (/usr/lib64/libpython2.7.so.1.0+0x4bd43)
    #17 0x7f7ef3398087 in PyEval_EvalFrameEx (/usr/lib64/libpython2.7.so.1.0+0xe5087)
    #18 0x7f7ef33982da in PyEval_EvalFrameEx (/usr/lib64/libpython2.7.so.1.0+0xe52da)
    #19 0x7f7ef339c10b in PyEval_EvalCodeEx (/usr/lib64/libpython2.7.so.1.0+0xe910b)
    #20 0x7f7ef33242a2  (/usr/lib64/libpython2.7.so.1.0+0x712a2)
    #21 0x7f7ef32fed43 in PyObject_Call (/usr/lib64/libpython2.7.so.1.0+0x4bd43)
    #22 0x7f7ef3391fe7 in PyEval_CallObjectWithKeywords (/usr/lib64/libpython2.7.so.1.0+0xdefe7)
    #23 0x7f7ef33b320f in PyEval_CallFunction (/usr/lib64/libpython2.7.so.1.0+0x10020f)
    #24 0x2000001eeb25 in boost::python::detail::returnable<boost::python::api::object>::type boost::python::call<boost::python::api::object, boost::python::dict>(_object*, boost::python::dict const&, boost::type<boost::python::api::object>*) /usr/include/boost/python/call.hpp:66
    #25 0x2000001da1ec in boost::python::detail::dependent<boost::python::api::object, boost::python::dict>::type boost::python::api::object_operators<boost::python::api::object>::operator()<boost::python::dict>(boost::python::dict const&) const /usr/include/boost/python/object_call.hpp:19
    #26 0x2000001da1ec in PythonServer::CreateUniverse(std::map<int, PlayerSetupData, std::less<int>, std::allocator<std::pair<int const, PlayerSetupData> > >&) /mnt/another/srcs/GIT/freeorion/python/server/ServerFramework.cpp:114
    #27 0x200000495351 in ServerApp::GenerateUniverse(std::map<int, PlayerSetupData, std::less<int>, std::allocator<std::pair<int const, PlayerSetupData> > >&) /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:1344
    #28 0x200000496f34 in ServerApp::NewGameInitConcurrentWithJoiners(GalaxySetupData const&, std::vector<PlayerSetupData, std::allocator<PlayerSetupData> > const&) /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:670
    #29 0x200000499e9d in ServerApp::NewMPGameInit(MultiplayerLobbyData const&) /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:624
    #30 0x200000507fae in WaitingForMPGameJoiners::react(CheckStartConditions const&) /mnt/another/srcs/GIT/freeorion/server/ServerFSM.cpp:1521
    #31 0x20000053363b in boost::statechart::detail::reaction_result boost::statechart::custom_reaction<CheckStartConditions>::react<WaitingForMPGameJoiners, boost::statechart::event_base, void const*>(WaitingForMPGameJoiners&, boost::statechart::event_base const&, void const* const&) /usr/include/boost/statechart/custom_reaction.hpp:41
    #32 0x20000053363b in boost::statechart::detail::reaction_result boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react_impl_non_empty::local_react_impl<boost::mpl::list4<boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> >, boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0> >(boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>&, boost::statechart::event_base const&, void const*) /usr/include/boost/statechart/simple_state.hpp:816
    #33 0x20000053363b in boost::statechart::detail::reaction_result boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react<boost::mpl::list4<boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> > >(boost::statechart::event_base const&, void const*) /usr/include/boost/statechart/simple_state.hpp:851
    #34 0x20000053363b in boost::statechart::detail::reaction_result boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react_impl_non_empty::local_react_impl<boost::mpl::list5<boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> >, boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0> >(boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>&, boost::statechart::event_base const&, void const*) /usr/include/boost/statechart/simple_state.hpp:820
    #35 0x20000053363b in boost::statechart::detail::reaction_result boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react<boost::mpl::list5<boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error> > >(boost::statechart::event_base const&, void const*) /usr/include/boost/statechart/simple_state.hpp:851
    #36 0x20000053363b in boost::statechart::detail::reaction_result boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react_impl_non_empty::local_react_impl<boost::mpl::list<boost::statechart::in_state_reaction<Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection>, boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0> >(boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>&, boost::statechart::event_base const&, void const*) /usr/include/boost/statechart/simple_state.hpp:820
    #37 0x20000053363b in boost::statechart::detail::reaction_result boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::local_react<boost::mpl::list<boost::statechart::in_state_reaction<Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection>, boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<CheckStartConditions>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<Hostless>, boost::statechart::custom_reaction<Error>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >(boost::statechart::event_base const&, void const*) /usr/include/boost/statechart/simple_state.hpp:851
    #38 0x20000053363b in boost::statechart::simple_state<WaitingForMPGameJoiners, ServerFSM, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) /usr/include/boost/statechart/simple_state.hpp:489
    #39 0x2000004c5c68 in boost::statechart::state_machine<ServerFSM, Idle, std::allocator<void>, boost::statechart::null_exception_translator>::process_queued_events() (/mnt/new/o01eg/games/freeorion-debug/bin/freeoriond+0x2000004c5c68)
    #40 0x2000004c60ce in boost::statechart::state_machine<ServerFSM, Idle, std::allocator<void>, boost::statechart::null_exception_translator>::process_event(boost::statechart::event_base const&) (/mnt/new/o01eg/games/freeorion-debug/bin/freeoriond+0x2000004c60ce)
    #41 0x20000048f0dd in ServerApp::HandleNonPlayerMessage(Message const&, std::shared_ptr<PlayerConnection>) /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:473
    #42 0x2000004a7627 in boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >::operator()(ServerApp*, Message const&, std::shared_ptr<PlayerConnection>) const /usr/include/boost/bind/mem_fn_template.hpp:280
    #43 0x2000004a7627 in void boost::_bi::list3<boost::_bi::value<ServerApp*>, boost::arg<1>, boost::arg<2> >::operator()<boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >, boost::_bi::rrlist2<Message, std::shared_ptr<PlayerConnection> > >(boost::_bi::type<void>, boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >&, boost::_bi::rrlist2<Message, std::shared_ptr<PlayerConnection> >&, int) /usr/include/boost/bind/bind.hpp:398
    #44 0x2000004a7627 in void boost::_bi::bind_t<void, boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >, boost::_bi::list3<boost::_bi::value<ServerApp*>, boost::arg<1>, boost::arg<2> > >::operator()<Message, std::shared_ptr<PlayerConnection> >(Message&&, std::shared_ptr<PlayerConnection>&&) /usr/include/boost/bind/bind.hpp:1318
    #45 0x2000004a7627 in boost::detail::function::void_function_obj_invoker2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, ServerApp, Message const&, std::shared_ptr<PlayerConnection> >, boost::_bi::list3<boost::_bi::value<ServerApp*>, boost::arg<1>, boost::arg<2> > >, void, Message, std::shared_ptr<PlayerConnection> >::invoke(boost::detail::function::function_buffer&, Message, std::shared_ptr<PlayerConnection>) /usr/include/boost/function/function_template.hpp:159
    #46 0x20000015c6f8 in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<boost::_bi::unspecified, boost::function<void (Message, std::shared_ptr<PlayerConnection>)>, boost::_bi::list2<boost::_bi::value<Message>, boost::_bi::value<std::shared_ptr<PlayerConnection> > > >, void>::invoke(boost::detail::function::function_buffer&) (/mnt/new/o01eg/games/freeorion-debug/bin/freeoriond+0x20000015c6f8)
    #47 0x20000013c7fd in boost::function0<void>::operator()() const /usr/include/boost/function/function_template.hpp:771
    #48 0x20000013c7fd in ServerNetworking::HandleNextEvent() /mnt/another/srcs/GIT/freeorion/network/ServerNetworking.cpp:513
    #49 0x20000046351e in ServerApp::Run() /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:327
    #50 0x200000463693 in ServerApp::operator()() /mnt/another/srcs/GIT/freeorion/server/ServerApp.cpp:177
    #51 0x2000003d3cd5 in main /mnt/another/srcs/GIT/freeorion/server/dmain.cpp:79
    #52 0x7f7ef086364f in __libc_start_main (/lib64/libc.so.6+0x2064f)
    #53 0x2000000db018 in _start (/mnt/new/o01eg/games/freeorion-debug/bin/freeoriond+0x2000000db018)

0x61100034dc48 is located 0 bytes to the right of 200-byte region [0x61100034db80,0x61100034dc48)
allocated by thread T0 here:
    #0 0x7f7ef532e612 in operator new(unsigned long) (/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libasan.so.2+0x99612)
    #1 0x7f7ef486f8cd in std::vector<short, std::allocator<short> >::_M_fill_assign(unsigned long, short const&) (/mnt/new/o01eg/games/freeorion-debug/lib64/freeorion/libfreeorioncommon.so+0x2000007a18cd)
    #2 0x7f7ef486bbdc in std::vector<short, std::allocator<short> >::assign(unsigned long, short const&) /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/stl_vector.h:489
    #3 0x7f7ef486bbdc in Pathfinder::PathfinderImpl::HandleCacheMiss(unsigned long, std::vector<short, std::allocator<short> >&) const /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:647
    #4 0x7f7ef4877305 in void boost::_mfi::cmf2<void, Pathfinder::PathfinderImpl, unsigned long, std::vector<short, std::allocator<short> >&>::call<Pathfinder::PathfinderImpl const* const, unsigned long, std::vector<short, std::allocator<short> > >(Pathfinder::PathfinderImpl const* const&, void const*, unsigned long&, std::vector<short, std::allocator<short> >&) const /usr/include/boost/bind/mem_fn_template.hpp:335
    #5 0x7f7ef4877305 in void boost::_mfi::cmf2<void, Pathfinder::PathfinderImpl, unsigned long, std::vector<short, std::allocator<short> >&>::operator()<Pathfinder::PathfinderImpl const*>(Pathfinder::PathfinderImpl const* const&, unsigned long, std::vector<short, std::allocator<short> >&) const /usr/include/boost/bind/mem_fn_template.hpp:345
    #6 0x7f7ef4877305 in void boost::_bi::list3<boost::_bi::value<Pathfinder::PathfinderImpl const*>, boost::arg<1>, boost::arg<2> >::operator()<boost::_mfi::cmf2<void, Pathfinder::PathfinderImpl, unsigned long, std::vector<short, std::allocator<short> >&>, boost::_bi::rrlist2<unsigned long&, std::vector<short, std::allocator<short> >&> >(boost::_bi::type<void>, boost::_mfi::cmf2<void, Pathfinder::PathfinderImpl, unsigned long, std::vector<short, std::allocator<short> >&>&, boost::_bi::rrlist2<unsigned long&, std::vector<short, std::allocator<short> >&>&, int) /usr/include/boost/bind/bind.hpp:398
    #7 0x7f7ef4877305 in void boost::_bi::bind_t<void, boost::_mfi::cmf2<void, Pathfinder::PathfinderImpl, unsigned long, std::vector<short, std::allocator<short> >&>, boost::_bi::list3<boost::_bi::value<Pathfinder::PathfinderImpl const*>, boost::arg<1>, boost::arg<2> > >::operator()<unsigned long&, std::vector<short, std::allocator<short> >&>(unsigned long&, std::vector<short, std::allocator<short> >&) /usr/include/boost/bind/bind.hpp:1318
    #8 0x7f7ef4877305 in boost::detail::function::void_function_obj_invoker2<boost::_bi::bind_t<void, boost::_mfi::cmf2<void, Pathfinder::PathfinderImpl, unsigned long, std::vector<short, std::allocator<short> >&>, boost::_bi::list3<boost::_bi::value<Pathfinder::PathfinderImpl const*>, boost::arg<1>, boost::arg<2> > >, void, unsigned long&, std::vector<short, std::allocator<short> >&>::invoke(boost::detail::function::function_buffer&, unsigned long&, std::vector<short, std::allocator<short> >&) /usr/include/boost/function/function_template.hpp:159
    #9 0x7f7ef48700b0 in boost::function2<void, unsigned long&, std::vector<short, std::allocator<short> >&>::operator()(unsigned long&, std::vector<short, std::allocator<short> >&) const /usr/include/boost/function/function_template.hpp:771
    #10 0x7f7ef485b67b in examine_row /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:194
    #11 0x7f7ef486313e in Pathfinder::PathfinderImpl::WithinJumps(unsigned long, std::vector<int, std::allocator<int> > const&) const /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:1056
    #12 0x7f7ef48635ad in Pathfinder::WithinJumps(unsigned long, std::vector<int, std::allocator<int> > const&) const /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:1032
    #13 0x20000019c437 in SystemsWithinJumps /mnt/another/srcs/GIT/freeorion/python/server/ServerWrapper.cpp:971
    #14 0x2000001b2ba1 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<boost::python::list (*)(unsigned long, boost::python::list), boost::python::default_call_policies, boost::mpl::vector3<boost::python::list, unsigned long, boost::python::list> > >::operator()(_object*, _object*) (/mnt/new/o01eg/games/freeorion-debug/bin/freeoriond+0x2000001b2ba1)
    #15 0x7f7ef309332c in boost::python::objects::function::call(_object*, _object*) const (/usr/lib64/libboost_python-2.7.so.1.62.0+0x2b32c)

SUMMARY: AddressSanitizer: heap-buffer-overflow /mnt/another/srcs/GIT/freeorion/universe/Pathfinder.cpp:1025 Pathfinder::PathfinderImpl::WithinJumpsCacheHit(std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> >*, unsigned long, unsigned long, std::vector<short, std::allocator<short> >&) const
Shadow bytes around the buggy address:
  0x0c2280061b30: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280061b40: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c2280061b50: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c2280061b60: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c2280061b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c2280061b80: 00 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa
  0x0c2280061b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2280061ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2280061bb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2280061bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2280061bd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==2372==ABORTING
```

### Expected Result
Server starts new game.

### Steps to reproduce
*    Run the server in the hostless mode.
*    Connect client and start game, make some turns.
*    Resing and connect again.
*    Start next game.

**Comment by o01eg** [comment]
Server log: https://gist.github.com/o01eg/a66069da64fd71aa37828f69ae4a6e70

**Comment by LGM-Doyle** [comment]
I think that this issue and #1824 both have the same underlying cause, memory leaks during startup.  I am working on a fix.

**Comment by LGM-Doyle** [comment]
I was unable to replicate this crash.

From the crash report it appears to have been caused by AddressSanitizer, which is a heap analysis tool that is compiled and linked with the executable it is testing.  It typically allocates much more memory than the application would allocate on its own.

Can this crash be replicated with an unmodified master?

**Comment by o01eg** [comment]
It was on unmodified master.

**Comment by Vezzra** [comment]
@o01eg, @LGM-Doyle, #1732 has been merged, did that fix the heap-buffer-overflow issue? Can we close this?

**Comment by LGM-Doyle** [comment]
Yes, this specific issue is fixed.  

However, hostless changes the fundamental server assumption that the server is started once, begins or loads a game and then exits.  There will be other bugs of a similar nature.  @o01eg has already posted the next such issue, #1897.  I can not foresee the scope of all of the fixes.  If hostless is an essential feature of v0.4.8, then fixing all of the problems may delay the release.
