### ISSUE TITLE
Travis CI is broken

### ISSUE THREAD

**Issue by agrrr3** [freeorion/freeorion#2372]
Looks the Travis CI is broken. See e.g.  https://travis-ci.org/freeorion/freeorion/jobs/488304756
```
01:29:42.293117 [error] python : configure_logging.py:199 : KeyError: 'handlers'
01:29:42.293141 [error] python : configure_logging.py:199 : 
01:29:42.293364 [error] ai : AIClientApp.cpp:196 : AIClientApp failed due to error in python AI code for AI_1.  Exiting Soon. id = -1
terminate called after throwing an instance of 'std::runtime_error'
```
Note there may be more issues in there.

**Comment by Morlic-fo** [comment]
Relevant part of the log:
```
01:29:42.292859 [error] python : configure_logging.py:199 : Uncaught exception: Traceback (most recent call last):
01:29:42.293037 [error] python : configure_logging.py:199 :   File "/freeorion/default/python/AI/FreeOrionAI.py", line 374, in <module>
01:29:42.293065 [error] python : configure_logging.py:199 :     init_handlers(fo.getOptionsDBOptionStr("ai-config"), fo.getAIDir())
01:29:42.293084 [error] python : configure_logging.py:199 :   File "/freeorion/build/default/python/common/handlers.py", line 11, in init_handlers
01:29:42.293101 [error] python : configure_logging.py:199 :     handlers = split(get_option_dict()[HANDLERS])
01:29:42.293092 [debug] server : Message.cpp:895 : ExtractJoinGameMessageData() from Default_Player_Name_in_WaitingForSPGameJoiners::react(const JoinGame& msg) client type -1
01:29:42.293117 [error] python : configure_logging.py:199 : KeyError: 'handlers'
01:29:42.293141 [error] python : configure_logging.py:199 : 
01:29:42.293364 [error] ai : AIClientApp.cpp:196 : AIClientApp failed due to error in python AI code for AI_1.  Exiting Soon. id = -1
terminate called after throwing an instance of 'std::runtime_error'
  what():  PythonAI failed to initialize.
```

**Comment by geoffthemedio** [comment]
I don't see the errors mentioned earlier in comments, but the "travis-ci/push" builds seem to randomly fail or not fail the "C++" test. eg.
https://travis-ci.org/freeorion/freeorion/builds/585164449
and
https://travis-ci.org/freeorion/freeorion/builds/585170881

one of which passed and one didn't pass, apparently due to
`3 - SmokeTestHostless (Failed)`
due to
````
10:31:13.206168 {0x00007fa269941480} [error] test : ClientAppFixture.cpp:115 : Disconnected
/freeorion/test/system/SmokeTestHostless.cpp:148: error: fatal error: in "SmokeTestHostless/hostless_server": critical check ProcessMessages(start_time, MAX_WAITING_SEC) has failed
````

**Comment by Morlic-fo** [comment]
@geoffthemedio CI broken by your commit https://github.com/freeorion/freeorion/commit/b7cd0fef4f44652d5520632f5b210d9958be1d7e

```/freeorion/universe/Condition.cpp:9550:23: error: use of 'auto' in lambda parameter declaration only available with -std=c++14 or -std=gnu++14```

**Comment by geoffthemedio** [comment]
Hopefully fixed https://github.com/freeorion/freeorion/commit/e5d09075fcc8102dd3490e21477757d21c3fe3fd

**Comment by adrianbroher** [comment]
I don't see anything in this issue, which is not fixed in the latest master or cannot be fixed because of infrastructure problems.

Can this issue be closed?
