### ISSUE TITLE
AI_Error

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#2517]
```
[31 七月 16:27:30] AI_5: AI_Error: AI script error : FreeOrionAI.py:generateOrders():338  - Exception float division by zero while trying to issue_fleet_orders_for_fleet_missions
Traceback (most recent call last):
  File "F:/Game\fo\FreeOrion\default\python\AI\FreeOrionAI.py", line 335, in generateOrders
    action()
  File "F:/Game\fo\FreeOrion\default\python\AI\FleetUtilsAI.py", line 588, in issue_fleet_orders_for_fleet_missions
    mission.issue_fleet_orders()
  File "F:/Game\fo\FreeOrion\default\python\AI\AIFleetMission.py", line 591, in issue_fleet_orders
    allocations=allocations)
  File "F:/Game\fo\FreeOrion\default\python\AI\MilitaryAI.py", line 954, in assign_military_fleets_to_systems
    sys_id = max(systems, key=lambda x: system_score(fid, x))
  File "F:/Game\fo\FreeOrion\default\python\AI\MilitaryAI.py", line 954, in <lambda>
    sys_id = max(systems, key=lambda x: system_score(fid, x))
  File "F:/Game\fo\FreeOrion\default\python\AI\MilitaryAI.py", line 945, in system_score
    weight = 1 / float(state.get_distance_to_enemy_supply(_sys_id))**1.25
ZeroDivisionError: float division by zero
```

I don't know how to reproduce it. Everything is fine on my side. This error just comes out from message window, I don't know what's wrong.

My version is : build-2019-7-30

And, it comes out 2 times in 2 consecutive turns.

**Comment by Morlic-fo** [comment]
Thanks for the report. Fixed by #2518.

Since only changes in python script are required, you can apply the bugfix and continue with your game without compiling / downloading new binaries.
