### ISSUE TITLE
freeorion dumps core when its window is closed

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2662]
### Environment

* **FreeOrion Version**: ed443e92df91490260f22542d204dd63e03f2c6f
* **Operating System**: Gentoo GNU/Linux
* **Graphic card used**: intel
* **Fetched as** 
  * Weekly development build
  * Compiled from source

### Description

```
[2019-12-03 02:40:23.803641] [0x00007f70f0ef3780] [info]    Audio disabled.
terminate called after throwing an instance of 'boost::wrapexcept<boost::log::v2_mt_posix::system_error>'
  what():  Failed to set TLS value: Invalid argument

[1]  + abort (core dumped)  ./freeorion
```

### Expected Result
clean shutdown

### Steps to reproduce
It is not always reproducible. Run some game in windowed mode and close the window.

**Comment by l29ah** [comment]
backtrace:
```
#0  0x00007f70f13537bb in raise () from /lib64/libc.so.6
#1  0x00007f70f133b55d in abort () from /lib64/libc.so.6
#2  0x00007f70f16ec6fd in __gnu_cxx::__verbose_terminate_handler ()
    at /var/tmp/portage/sys-devel/gcc-9.2.0-r2/work/gcc-9.2.0/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f70f171c7e8 in __cxxabiv1::__terminate (handler=<optimized out>)
    at /var/tmp/portage/sys-devel/gcc-9.2.0-r2/work/gcc-9.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f70f171c833 in std::terminate ()
    at /var/tmp/portage/sys-devel/gcc-9.2.0-r2/work/gcc-9.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007f70f171ca63 in __cxxabiv1::__cxa_throw (obj=<optimized out>, 
    tinfo=0x7f70f21f1860 <typeinfo for boost::wrapexcept<boost::log::v2_mt_posix::system_error>>, 
    dest=0x7f70f217ee30 <boost::wrapexcept<boost::log::v2_mt_posix::system_error>::~wrapexcept()>)
    at /var/tmp/portage/sys-devel/gcc-9.2.0-r2/work/gcc-9.2.0/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007f70f218421f in void boost::throw_exception<boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> >(boost::exception_detail::error_info_injector<boost::log::v2_mt_posix::system_error> const&) ()
   from /usr/lib64/libboost_log.so.1.71.0
#7  0x00007f70f217bd1f in boost::log::v2_mt_posix::system_error::throw_(char const*, unsigned long, char const*, int) ()
   from /usr/lib64/libboost_log.so.1.71.0
#8  0x00007f70f219a022 in boost::log::v2_mt_posix::aux::thread_specific_base::set_content(void*) const ()
   from /usr/lib64/libboost_log.so.1.71.0
#9  0x00007f70f2172923 in boost::log::v2_mt_posix::sources::aux::get_severity_level() () from /usr/lib64/libboost_log.so.1.71.0
#10 0x000056034647461c in boost::log::v2_mt_posix::record boost::log::v2_mt_posix::sources::basic_composite_logger<char, boost::log::v2_mt_posix::sources::severity_channel_logger_mt<LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::log::v2_mt_posix::sources::multi_thread_model<boost::log::v2_mt_posix::aux::light_rw_mutex>, boost::log::v2_mt_posix::sources::features<boost::log::v2_mt_posix::sources::severity<LogLevel>, boost::log::v2_mt_posix::sources::channel<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::open_record<boost::parameter::aux::tagged_argument_list_of_1<boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> > >(boost::parameter::aux::tagged_argument_list_of_1<boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> > const&) ()
#11 0x00005603464f7434 in ClientNetworking::Impl::NetworkingThread(std::shared_ptr<ClientNetworking const>) ()
#12 0x000056034650729a in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf1<void, ClientNetworking::Impl, std::shared_ptr<ClientNetworking const> >, boost::_bi::list2<boost::_bi::value<ClientNetworking::Impl*>, boost::_bi::value<std::shared_ptr<ClientNetworking const> > > > >::run() ()
#13 0x00007f70f1a9636e in thread_proxy () from /usr/lib64/libboost_thread.so.1.71.0
#14 0x00007f70f2037380 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f70f1423bff in clone () from /lib64/libc.so.6
```
