### ISSUE TITLE
AI Script Error

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#2794]
I'm getting this in the in-game chat after loading the attached save and hitting turn:
````
[18 Mar 16:49:46] AI_2: AI_Error: AI script error : FreeOrionAI.py:generateOrders():338  - Exception dictionary changed size during iteration while trying to generate_resources_orders
Traceback (most recent call last):
  File "C:/Users\Geoff\Desktop\FOSDK11\FreeOrionAlt\default\python\AI\FreeOrionAI.py", line 335, in generateOrders
    action()
  File "C:/Users\Geoff\Desktop\FOSDK11\FreeOrionAlt\default\python\AI\ResourcesAI.py", line 735, in generate_resources_orders
    set_planet_resource_foci()
  File "C:/Users\Geoff\Desktop\FOSDK11\FreeOrionAlt\default\python\AI\ResourcesAI.py", line 714, in set_planet_resource_foci
    set_planet_production_and_research_specials(focus_manager)
  File "C:/Users\Geoff\Desktop\FOSDK11\FreeOrionAlt\default\python\AI\ResourcesAI.py", line 483, in set_planet_production_and_research_specials
    for pid, pinfo in focus_manager.raw_planet_info.items():
RuntimeError: dictionary changed size during iteration
````

[War 3.zip](https://github.com/freeorion/freeorion/files/4349921/War.3.zip)

Relevant code is here: https://github.com/freeorion/freeorion/blob/master/default/python/AI/ResourcesAI.py#L483

**Comment by geoffthemedio** [comment]
Something similar after starting a new game:
````
[19 Mar 16:04:57] AI_4: AI_Error: AI script error : FreeOrionAI.py:generateOrders():338  - Exception dictionary changed size during iteration while trying to generate_resources_orders
Traceback (most recent call last):
  File "C:/Users\Geoff\Desktop\FOSDK11\FreeOrionAlt\default\python\AI\FreeOrionAI.py", line 335, in generateOrders
    action()
  File "C:/Users\Geoff\Desktop\FOSDK11\FreeOrionAlt\default\python\AI\ResourcesAI.py", line 735, in generate_resources_orders
    set_planet_resource_foci()
  File "C:/Users\Geoff\Desktop\FOSDK11\FreeOrionAlt\default\python\AI\ResourcesAI.py", line 722, in set_planet_resource_foci
    set_planet_industry_and_research_foci(focus_manager, priority_ratio)
  File "C:/Users\Geoff\Desktop\FOSDK11\FreeOrionAlt\default\python\AI\ResourcesAI.py", line 561, in set_planet_industry_and_research_foci
    for pid, pinfo in focus_manager.raw_planet_info.items():
RuntimeError: dictionary changed size during iteration
````
