### ISSUE TITLE
Closing socket could lead to server freeze

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#2816]
### Environment
* **FreeOrion Version**: https://github.com/o01eg/freeorion/commit/2de79d16190511016280287bb92ee63623a5d072 based on https://github.com/o01eg/freeorion/commit/025f5451ae2df8ea3335de528edcb8cda7e11000
* **Operating System**: Ubuntu 18.04 AMD64
* **Fetched as** 
  * Compiled from source

### Description

Any connections are stopped to processed which could looks like black screen when connecting to the server

Coredump shows:
```
#0  0x00007f6bfdce6447 in __close (fd=fd@entry=13) at ../sysdeps/unix/sysv/linux/close.c:27
#1  0x000055a1389b0984 in boost::asio::detail::socket_ops::close (s=13, state=@0x55a13a841e94: 82 'R', destruction=destruction@entry=false, ec=...) at /usr/include/boost/asio/detail/impl/socket_ops.ipp:319
#2  0x000055a1389b256f in boost::asio::detail::reactive_socket_service_base::close (ec=..., impl=..., this=0x55a13a842598) at /usr/include/boost/asio/detail/impl/reactive_socket_service_base.ipp:108
#3  boost::asio::stream_socket_service<boost::asio::ip::tcp>::close (ec=..., impl=..., this=<optimized out>) at /usr/include/boost/asio/stream_socket_service.hpp:174
#4  boost::asio::basic_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >::close (this=this@entry=0x55a13a841e90) at /usr/include/boost/asio/basic_socket.hpp:355
#5  0x000055a1389a6e44 in PlayerConnection::~PlayerConnection (this=<optimized out>, __in_chrg=<optimized out>) at ./server/ServerNetworking.cpp:196
#6  0x000055a1389b6872 in std::_Sp_counted_ptr<PlayerConnection*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:376
#7  0x000055a138801e56 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x55a13a843af0) at /usr/include/c++/7/bits/shared_ptr_base.h:154
#8  0x000055a1389b2c52 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x55a13b677f78, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#9  std::__shared_ptr<PlayerConnection, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x55a13b677f70, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:1123
#10 std::shared_ptr<PlayerConnection>::~shared_ptr (this=0x55a13b677f70, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr.h:93
#11 boost::_bi::value<std::shared_ptr<PlayerConnection> >::~value (this=0x55a13b677f70, __in_chrg=<optimized out>) at /usr/include/boost/bind/bind.hpp:118
#12 boost::_bi::storage1<boost::_bi::value<std::shared_ptr<PlayerConnection> > >::~storage1 (this=0x55a13b677f70, __in_chrg=<optimized out>) at /usr/include/boost/bind/storage.hpp:40
#13 boost::_bi::list1<boost::_bi::value<std::shared_ptr<PlayerConnection> > >::~list1 (this=0x55a13b677f70, __in_chrg=<optimized out>) at /usr/include/boost/bind/bind.hpp:223
#14 boost::_bi::bind_t<boost::_bi::unspecified, boost::function<void (std::shared_ptr<PlayerConnection>)>, boost::_bi::list1<boost::_bi::value<std::shared_ptr<PlayerConnection> > > >::~bind_t() (this=0x55a13b677f50, 
    __in_chrg=<optimized out>) at /usr/include/boost/bind/bind.hpp:1275
#15 0x000055a1389b2d50 in boost::detail::function::functor_manager<boost::_bi::bind_t<boost::_bi::unspecified, boost::function<void (std::shared_ptr<PlayerConnection>)>, boost::_bi::list1<boost::_bi::value<std::shared_ptr<PlayerConnection> > > > >::manager(boost::detail::function::function_buffer const&, boost::detail::function::function_buffer&, boost::detail::function::functor_manager_operation_type, mpl_::bool_<false>) (op=<optimized out>, out_buffer=..., 
    in_buffer=...) at /usr/include/boost/function/function_base.hpp:358
#16 boost::detail::function::functor_manager<boost::_bi::bind_t<boost::_bi::unspecified, boost::function<void (std::shared_ptr<PlayerConnection>)>, boost::_bi::list1<boost::_bi::value<std::shared_ptr<PlayerConnection> > > > >::manager(boost::detail::function::function_buffer const&, boost::detail::function::function_buffer&, boost::detail::function::functor_manager_operation_type, boost::detail::function::function_obj_tag) (op=<optimized out>, out_buffer=..., 
    in_buffer=...) at /usr/include/boost/function/function_base.hpp:379
#17 boost::detail::function::functor_manager<boost::_bi::bind_t<boost::_bi::unspecified, boost::function<void (std::shared_ptr<PlayerConnection>)>, boost::_bi::list1<boost::_bi::value<std::shared_ptr<PlayerConnection> > > > >::manage(boost::detail::function::function_buffer const&, boost::detail::function::function_buffer&, boost::detail::function::functor_manager_operation_type) (in_buffer=..., out_buffer=..., op=<optimized out>)
    at /usr/include/boost/function/function_base.hpp:407
#18 0x000055a1389a5b78 in boost::detail::function::basic_vtable0<void>::clear (this=<optimized out>, functor=...) at /usr/include/boost/function/function_template.hpp:510
#19 boost::function0<void>::clear (this=0x7fff13ac2c50) at /usr/include/boost/function/function_template.hpp:868
#20 boost::function0<void>::~function0 (this=0x7fff13ac2c50, __in_chrg=<optimized out>) at /usr/include/boost/function/function_template.hpp:752
#21 boost::function<void ()>::~function() (this=0x7fff13ac2c50, __in_chrg=<optimized out>) at /usr/include/boost/function/function_template.hpp:1041
#22 ServerNetworking::HandleNextEvent (this=this@entry=0x7fff13ac39a8) at ./server/ServerNetworking.cpp:720
#23 0x000055a138909db0 in ServerApp::Run (this=0x7fff13ac2ef0) at ./server/ServerApp.cpp:330
#24 0x000055a1387e165e in main (argc=<optimized out>, argv=<optimized out>) at ./server/dmain.cpp:95
```

### Expected Result
Closing of socked is processed asynchronously.

**Comment by geoffthemedio** [comment]
Could you elaborate on when / how this issue would happen?

**Comment by o01eg** [comment]
@geoffthemedio It happened once when I tested multiplayer game. Network issues are hard to reproduce.
