### ISSUE TITLE
Segfault in CanMountInSlotType

### ISSUE THREAD

**Issue by l29ah** [freeorion/freeorion#2881]
### Environment

* **FreeOrion Version**: b2112feb2fbf6adcfe8b5c2b86f1abb0ab32da98
* **Operating System**: Gentoo GNU/Linux
* **Fetched as** 
  * Compiled from source

### Description
```
(gdb) bt
#0  0x00007ff5c4ff4488 in ShipPart::CanMountInSlotType(ShipSlotType) const () from /home/l29ah/projects/freeorion/build/libfreeorioncommon.so
#1  0x000056494eeaf02b in DesignWnd::MainPanel::FindEmptySlotForPart(ShipPart const*) ()
#2  0x000056494eece019 in DesignWnd::MainPanel::AddPart(ShipPart const*) ()
#3  0x000056494eeffa6a in boost::signals2::detail::signal_impl<void (ShipPart const*), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (ShipPart const*)>, boost::function<void (boost::signals2::connection const&, ShipPart const*)>, boost::signals2::mutex>::operator()(ShipPart const*) ()
#4  0x000056494eeffc30 in boost::detail::function::void_function_obj_invoker1<boost::signals2::detail::weak_signal<void (ShipPart const*), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (ShipPart const*)>, boost::function<void (boost::signals2::connection const&, ShipPart const*)>, boost::signals2::mutex>, void, ShipPart const*>::invoke(boost::detail::function::function_buffer&, ShipPart const*) ()
#5  0x000056494eeffa6a in boost::signals2::detail::signal_impl<void (ShipPart const*), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (ShipPart const*)>, boost::function<void (boost::signals2::connection const&, ShipPart const*)>, boost::signals2::mutex>::operator()(ShipPart const*) ()
#6  0x000056494eeffc30 in boost::detail::function::void_function_obj_invoker1<boost::signals2::detail::weak_signal<void (ShipPart const*), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (ShipPart const*)>, boost::function<void (boost::signals2::connection const&, ShipPart const*)>, boost::signals2::mutex>, void, ShipPart const*>::invoke(boost::detail::function::function_buffer&, ShipPart const*) ()
#7  0x000056494eeffa6a in boost::signals2::detail::signal_impl<void (ShipPart const*), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (ShipPart const*)>, boost::function<void (boost::signals2::connection const&, ShipPart const*)>, boost::signals2::mutex>::operator()(ShipPart const*) ()
#8  0x00007ff5c3db7786 in GG::Wnd::HandleEvent(GG::WndEvent const&) () from /home/l29ah/projects/freeorion/build/libGiGi.so
#9  0x00007ff5c3d17c02 in GG::GUIImpl::HandleMouseButtonRelease(unsigned int, GG::Pt const&, int) () from /home/l29ah/projects/freeorion/build/libGiGi.so
#10 0x000056494f1583a4 in SDLGUI::HandleSystemEvents() ()
#11 0x000056494ed4fecd in HumanClientApp::HandleSystemEvents() ()
#12 0x00007ff5c3d1bc99 in GG::GUI::RunModal(std::shared_ptr<GG::Wnd>, bool&) () from /home/l29ah/projects/freeorion/build/libGiGi.so
#13 0x000056494f1578cc in SDLGUI::Run() ()
#14 0x000056494ed2ab03 in mainSetupAndRun() ()
#15 0x000056494ed218bd in main ()
```

### Steps to reproduce

Make a new small hull design and try to install a mass driver there.

**Comment by Oberlus** [comment]
It crashes when trying to mount a part by double-clicking in the part.

Drag&drop parts into slots does not crash.
Removing parts from slots by either double-clicking or drag&drop does not crash.

**Comment by Oberlus** [comment]
More on this:

- Any hull and any part will cause the crash (it does not matter if there is a valid slot for the clicked part).
- Server log just says the only human player disconnected (at 09:41:57), and so server exits (cleanly).
- Client log:
```
09:41:49.359987 {0x00007f49ab1a8800} [debug] client : HumanClientApp.cpp:735 : Save games completed.
09:41:52.337746 {0x00007f49ab1a8800} [debug] client : DesignWnd.cpp:2473 : BasesListBox::Populate
09:41:52.337951 {0x00007f49ab1a8800} [debug] client : DesignWnd.cpp:2614 : EmptyHulls::PopulateCore EmpireID(): 1
09:41:52.337970 {0x00007f49ab1a8800} [error] client : DesignWnd.cpp:2622 : EmptyHulls::PopulateCoreordered has fewer than expected entries...
09:41:52.357635 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : EncyclopediaDetailPanel::DoLayout - m_scroll_panel->SizeMove time:     4387 µs
09:41:52.357660 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:253 : EncyclopediaDetailPanel::DoLayout                            time:     4444 µs
09:41:54.832501 {0x00007f49ab1a8800} [debug] client : DesignWnd.cpp:2473 : BasesListBox::Populate
09:41:54.832790 {0x00007f49ab1a8800} [debug] client : DesignWnd.cpp:2614 : EmptyHulls::PopulateCore EmpireID(): 1
09:41:54.832828 {0x00007f49ab1a8800} [error] client : DesignWnd.cpp:2622 : EmptyHulls::PopulateCoreordered has fewer than expected entries...
09:41:54.834130 {0x00007f49ab1a8800} [debug] client : EncyclopediaDetailPanel.cpp:2308 : default enemy stats:: tech_level: 0.0025   DR: 0.05   attack: 3.0675
09:41:54.841058 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : Effect TargetSets Evaluation - species         time:     3012 µs
09:41:54.841095 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : Effect TargetSets Evaluation - specials        time:       77 µs
09:41:54.841112 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : Effect TargetSets Evaluation - techs           time:      937 µs
09:41:54.841126 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : Effect TargetSets Evaluation - buildings       time:      813 µs
09:41:54.841140 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : Effect TargetSets Evaluation - ship hull/parts time:     1459 µs
09:41:54.841153 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : Effect TargetSets Evaluation - fields          time:       10 µs
09:41:54.841166 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : Effect TargetSets Evaluation - eval waiting    time:       43 µs
09:41:54.841180 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:243 : Effect TargetSets Evaluation - reordering      time:       12 µs
09:41:54.841194 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:253 : Effect TargetSets Evaluation                   time:     6368 µs
09:41:54.841415 {0x00007f49ab1a8800} [debug] timer : ScopedTimer.cpp:35 : Universe::UpdateMeterEstimatesImpl on 1 objects time:     7171 µs
09:41:54.841496 {0x00007f49ab1a8800} [debug] client : Universe.cpp:2867 : Universe::Delete with ID: -2
```

**Comment by Oberlus** [comment]
I'm in the process of bisecting this.

Commit ac7b2dda83eefcd7faa23601fa57a2635d8a5202 was good.

~~I'll edit this comment when I find the culprit.~~

```
caa6f1313f6f331a819d521f2dd43319b09814e3 is the first bad commit
commit caa6f1313f6f331a819d521f2dd43319b09814e3
Author: Marcel Metz <mmetz@adrian-broher.net>
Date:   Sat Apr 18 01:14:26 2020 +0200
```
So it was @adrianbroher commit caa6f1313f6f331a819d521f2dd43319b09814e3
Someone please look into this.

**Comment by adrianbroher** [comment]
@Oberlus looking into it.

**Comment by adrianbroher** [comment]
@Oberlus Thanks for doing the extensive bughunt.
