### ISSUE TITLE
NaN to integer error in AI script

### ISSUE THREAD

**Issue by urshmost** [freeorion/freeorion#2907]
### Environment

* **FreeOrion Version**:  build 2020 04 20
* **Operating System**:  Win 10 64 bit
* **Graphic card used**:  
* **Fetched as**   * Weekly development build

### Description
on the start of turn 251 the message window popped open with the following errors:

````
[28 Apr 14:49:34] AI_2: AI_Error: AI script error : FreeOrionAI.py:generateOrders():360  - Exception cannot convert float NaN to integer while trying to calculate_priorities
Traceback (most recent call last):
  File "F:/FreeOrion\default\python\AI\FreeOrionAI.py", line 357, in generateOrders
    action()
  File "F:/FreeOrion\default\python\AI\PriorityAI.py", line 47, in calculate_priorities
    InvasionAI.get_invasion_fleets()  # sets AIstate.opponentPlanetIDs, and AIstate.invasionTargetedPlanetIDs
  File "F:/FreeOrion\default\python\AI\InvasionAI.py", line 214, in get_invasion_fleets
    evaluated_planets = assign_invasion_values(evaluated_planet_ids)
  File "F:/FreeOrion\default\python\AI\InvasionAI.py", line 275, in assign_invasion_values
    planet_values[pid] = neighbor_values.setdefault(pid, evaluate_invasion_planet(pid, secure_missions))
  File "F:/FreeOrion\default\python\AI\InvasionAI.py", line 480, in evaluate_invasion_planet
    ships_needed = math.ceil((planned_troops+_TROOPS_SAFETY_MARGIN) / float(troops_per_ship))
ValueError: cannot convert float NaN to integer
````

This error was repeated for A1_5 and A1_1.

I exited the game, restarted, and reloaded the end of turn 250 save file and the error repeated.

Save game file:
[FreeOrion_250.zip](https://github.com/freeorion/freeorion/files/4548843/FreeOrion_250.zip)

Also attach the log files the game creates:

[log files.zip](https://github.com/freeorion/freeorion/files/4548911/log.files.zip)

### Steps to reproduce
load the turn 250 save game and advance to the next turn.

**Comment by Morlic-fo** [comment]
Seems to be some bug in the troop meter calculations.

```
troops = planet.currentMeterValue(fo.meterType.troops)
troop_regen = planet.currentMeterValue(fo.meterType.troops) - planet.initialMeterValue(fo.meterType.troops)
max_troops = planet.currentMeterValue(fo.meterType.maxTroops)
debug("Troops: %f, Regen: %f, Jumps: %f, Time: %f, Max: %f", troops, troop_regen, max_jumps, build_time, max_troops)

01:37:50.761509 {0x00002b1c} [debug] python : InvasionAI.py:451 : python : Invasion eval of P_2338<Adams γ I>
...
01:37:50.762509 {0x00002b1c} [debug] python : InvasionAI.py:479 : python : Troops: nan, Regen: nan, Jumps: 25.000000, Time: 7.000000, Max: nan
```

Human Client on that planet is also showing weird stuff / incomplete calculations:
![NaNTroops](https://user-images.githubusercontent.com/11706951/80548294-e78e3380-89ba-11ea-86ae-fe6e9163fd99.PNG)

I don't see warnings/errors in server log.

**Comment by geoffthemedio** [comment]
If the bad value is already in the save, I probably can't do much to prevent it. If a save that doesn't have it reproducibly causes it to appear, that would be helpful.

Otherwise, I could add some safety / sanity checks to set values of NaN back to 0 whenever they are found...

**Comment by urshmost** [comment]
sorry, previous saves were wiped when I started a new game to test and didn't realize that cleared out all autosave files.

**Comment by Vezzra** [comment]
As this is a release-blocking issue that hasn't got any attention for over two weeks now, what is the status on this? Any hope it can be dealt with within reasonable time? Or can we at least put a workaround in place that doesn't cripple the AI too much?

@Morlic-fo? @geoffthemedio?

**Comment by geoffthemedio** [comment]
I can sometimes fix a save with some custom coding. I could add a bunch of sanity checks to the server to catch random NaN appearances in gamestate values, but I don't consider doing that release blocking if it's not reproducible. I don't know about the AI.

**Comment by Vezzra** [comment]
You're right, if the issue turns up only rarely, then it shouldn't be release blocking. However, I have no idea how frequent/common the issue is.

If the AI scripts throw exceptions, AIs won't do their turns properly anymore, effectively crippling them, AFAIK. Which is why I'm a bit cautious...

**Comment by exa18** [comment]
Same AI error BUT it throws after successfully alliance made.
```
AI_Error: AI script error : FreeOrionAI.py:generateOrders():360  - Exception 3330 while trying to issue_fleet_orders_for_fleet_missions
Traceback (most recent call last):
  File "/snap/freeorion/128/share/freeorion/default/python/AI/FreeOrionAI.py", line 357, in generateOrders
    action()
  File "/snap/freeorion/128/share/freeorion/default/python/AI/FleetUtilsAI.py", line 600, in issue_fleet_orders_for_fleet_missions
    mission.issue_fleet_orders()
  File "/snap/freeorion/128/share/freeorion/default/python/AI/AIFleetMission.py", line 506, in issue_fleet_orders
    thisround="Fleet %d Reassignment" % fleet_id)
  File "/snap/freeorion/128/share/freeorion/default/python/AI/MilitaryAI.py", line 763, in get_military_fleets
    interior_targets = [sid for sid in interior_targets1 if (
  File "/snap/freeorion/128/share/freeorion/default/python/AI/MilitaryAI.py", line 764, in <listcomp>
    allocation_helper.threat_bias + systems_status.get(sid, {}).get('totalThreat', 0) > 0.8 * allocation_helper.already_assigned_rating[sid])]
KeyError: 3330
```
### AND
```
AI_Error: AI script error : FreeOrionAI.py:generateOrders():360  - Exception 0 while trying to assign_military_fleets_to_systems
Traceback (most recent call last):
  File "/snap/freeorion/128/share/freeorion/default/python/AI/FreeOrionAI.py", line 357, in generateOrders
    action()
  File "/snap/freeorion/128/share/freeorion/default/python/AI/MilitaryAI.py", line 935, in assign_military_fleets_to_systems
    allocations = get_military_fleets(mil_fleets_ids=avail_mil_fleet_ids, try_reset=False, thisround=thisround)
  File "/snap/freeorion/128/share/freeorion/default/python/AI/MilitaryAI.py", line 763, in get_military_fleets
    interior_targets = [sid for sid in interior_targets1 if (
  File "/snap/freeorion/128/share/freeorion/default/python/AI/MilitaryAI.py", line 764, in <listcomp>
    allocation_helper.threat_bias + systems_status.get(sid, {}).get('totalThreat', 0) > 0.8 * allocation_helper.already_assigned_rating[sid])]
KeyError: 0
```

**Comment by Vezzra** [comment]
@exa18, can that be reproduced reliably?
