### ISSUE TITLE
Error when st-tool.py redirected to file on Windows

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#3012]
Windows 10, master

I got an error when trying to redirect output to the file.
If I redirect file to the console (PyCharm terminal) it works fine.

Command: 
```
freeorion\check>st-tool.py format "../default\stringtables\ru.txt" > text.txt
```

Error output:
```
Traceback (most recent call last):
  File "I:\projects\freeorion\check\st-tool.py", line 1036, in <module>
    sys.exit(args.action(args))
  File "I:\projects\freeorion\check\st-tool.py", line 777, in format_action
    print(source_st, end='', )
  File "C:\Users\sa\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to <undefined>
```

**Comment by adrianbroher** [comment]
Not a bug. BOM is a pest to be pruned from existence.

**Comment by adrianbroher** [comment]
https://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console
http://www.tiernok.com/posts/python-3-6-unicode-output-for-windows-console.html

**Comment by Cjkjvfnby** [comment]
> Not a bug. BOM is a pest to be pruned from existence.

Still, a bug.  This tool supposed to be easy to use for non-developers.

The first link is a bit outdated.  Python3.8 `print` is smarter. When it got a console as stdout it works fine. But then stdout is a file, it fails.  Setting env variable helps with it.

I would like to have a simple command for reformating file.  Maybe `st-tool.py format --self SOURCES`.  Let's discuss how it can look like, and I will implement it myself.

**Comment by adrianbroher** [comment]
> This tool supposed to be easy to use for non-developers.

Okay, you have a point there.  However the idea of prepending a Byte Order Mark on an encoding which has no byte order is still beyond idiotic.

From the PR you mentioned there are at least those things to consider:
- Input file encoding
- Input file line endings

This can be handled in two ways:

- Whenever the file is consumed the malformed encoding and line endings are discarded, the output file contains only the correct non-BOM UTF-8 encoding.  I don't like smartness as guessing the encoding of a file is not reliable and both line endings and encoding may be mixed and I don't see a reason why we should reimplement existing tools like `iconv` or `dos2unix` incomplete and badly.
- Consume the file and immediately fail with an error and exit code, whenever a non-UTF-8 unix line ending file is encountered.  The user who created the file does know what tool he used to save the file and can save the file again in the expected format.

> I would like to have a simple command for reformating file. Maybe st-tool.py format --self SOURCES. Let's discuss how it can look like, and I will implement it myself.

> Let's discuss how it can look like

Do you had something specific in mind for that question?  The only thing I would suggest  is using `-i, --in-place` as parameter.  Beause `sed` uses the same parameter so it's easier to remember for me.

From man sed(1)
```
       -i[SUFFIX], --in-place[=SUFFIX]

              edit files in place (makes backup if SUFFIX supplied)
```

**Comment by Cjkjvfnby** [comment]
Probably we should not warry a lot about line endings because of the git settings.

Users can have windows style locally and push with Unix style [1].  And we can validate it in CI.

> Consume the file and immediately fail with an error and exit code, whenever a non-UTF-8 unix line ending file is encountered. The user who created the file does know what tool he used to save the file and can save the file again in the expected format.

Sounds good, we can check it via CI.  Even notepad allows us to set file encoding.  

[1] https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings
