### ISSUE TITLE
Boost log segfaults in dockerized environment

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#3266]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 82513f559e392e4b229ce0527168f39bf7932161
* **Operating System**: Ubuntu Linux 18.04 LTS under Docker
* **Fetched as** 
  * Compiled from source

Description
-----------

Launching system tests leads to segfault:

```
Thread 22 "fo_systemtest_g" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f6aebfff700 (LWP 10298)]
0x00007f6b073154c3 in boost::log::v2_mt_posix::core::get_logging_enabled() const () from /usr/lib/x86_64-linux-gnu/libboost_log.so.1.62.0
(gdb) bt
#0  0x00007f6b073154c3 in boost::log::v2_mt_posix::core::get_logging_enabled() const () from /usr/lib/x86_64-linux-gnu/libboost_log.so.1.62.0
#1  0x00007f6b07e36f1a in boost::log::v2_mt_posix::sources::basic_composite_logger<char, boost::log::v2_mt_posix::sources::severity_channel_logger_mt<LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::log::v2_mt_posix::sources::multi_thread_model<boost::log::v2_mt_posix::aux::light_rw_mutex>, boost::log::v2_mt_posix::sources::features<boost::log::v2_mt_posix::sources::severity<LogLevel>, boost::log::v2_mt_posix::sources::channel<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::open_record<boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> > (this=0x55b7e08330a8, 
    args=...) at /usr/include/boost/log/sources/basic_logger.hpp:456
#2  0x00007f6b07fd5a9c in parse::file_substitution (
    text="Species\n    name = \"SP_GISGUFGTHRIM\"\n    description = \"SP_GISGUFGTHRIM_DESC\"\n    gameplay_description = \"SP_GISGUFGTHRIM_GAMEPLAY_DESC\"\n    Native\n    CanProduceShips\n\n    tags = [ \"ORGANIC\" \"BAD_IND"..., 
    file_search_path=...) at /freeorion/parse/Parse.cpp:218
#3  0x00007f6b07fd5da5 in parse::detail::parse_file_common (path=..., lexer=..., filename="/freeorion/build/default/scripting/species/SP_GISGUSGTHRIM.focs.txt", 
    file_contents="Species\n    name = \"SP_GISGUFGTHRIM\"\n    description = \"SP_GISGUFGTHRIM_DESC\"\n    gameplay_description = \"SP_GISGUFGTHRIM_GAMEPLAY_DESC\"\n    Native\n    CanProduceShips\n\n    tags = [ \"ORGANIC\" \"BAD_IND"..., first=non-dereferenceable iterator for std::vector, last=non-dereferenceable iterator for std::vector, it=...) at /freeorion/parse/Parse.cpp:499
#4  0x00007f6b0807707d in parse::detail::parse_file<(anonymous namespace)::grammar, std::map<std::__cxx11::basic_string<char>, std::unique_ptr<Species> > > (arg1=std::map with 41 elements = {...}, path=..., lexer=..., 
    this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>) at /freeorion/parse/ParseImpl.h:179
#5  parse::species[abi:cxx11](boost::filesystem::path const&) (path=...) at /freeorion/parse/SpeciesParser.cpp:404
...
```

Expected Result
---------------

System tests passed

Steps to reproduce
------------------

* Start docker `docker run -v <path to freeorion source>:/freeorion -v <build directory>:/freeorion/build -w /freeorion/build -it ubuntu:bionic /bin/bash`
* Install dependencies `# apt update && apt install cmake libboost1.62-all-dev`
* Build freeorion with tests `# cmake -DBUILD_CLIENT_GG=OFF -DBUILD_TESTING=ON ..`
* Launch test `# ./fo_systemtest_game`

**Comment by geoffthemedio** [comment]
is this stil an issue?

**Comment by o01eg** [comment]
Ubuntu Bionic is dropped so I'll re-try this issue with Ubuntu Focal and boost-1.71.

**Comment by o01eg** [comment]
Looks fine in new environment.
