### ISSUE TITLE
AI script Error [Version: 2021-02-09.cb4b741]

### ISSUE THREAD

**Issue by jinlan** [freeorion/freeorion#3311]
Happens in AI turn, don't know how to reproduce.

```
[16 二月 21:11:32] AI_4: AI_Error: AI script error : _freeorion_tools.py:assertion_fails():373  - Assertion failed: Can't split last ship from fleet. Traceback (most recent call last):   File "F:/Game\FreeOrion\default\python\AI\FreeOrionAI.py", line 70, in _error_handler
    res = func(*args, **kwargs)
  File "F:/Game/FreeOrion/default/python\common\listeners.py", line 42, in wrapper
    res = funct(*args)
  File "F:/Game\FreeOrion\default\python\AI\FreeOrionAI.py", line 348, in generateOrders
    action()
  File "F:/Game\FreeOrion\default\python\AI\FleetUtilsAI.py", line 594, in issue_fleet_orders_for_fleet_missions
    mission.issue_fleet_orders()
  File "F:/Game\FreeOrion\default\python\AI\AIFleetMission.py", line 546, in issue_fleet_orders
    new_fleet_id = FleetUtilsAI.split_ship_from_fleet(fleet_id, ship_id)
  File "F:/Game\FreeOrion\default\python\AI\FleetUtilsAI.py", line 237, in split_ship_from_fleet
    if assertion_fails(fleet.numShips > 1, "Can't split last ship from fleet"):

[16 二月 21:11:32] AI_4: AI_Error: AI script error : _freeorion_tools.py:assertion_fails():373  - Assertion failed! Traceback (most recent call last):   File "F:/Game\FreeOrion\default\python\AI\FreeOrionAI.py", line 70, in _error_handler
    res = func(*args, **kwargs)
  File "F:/Game/FreeOrion/default/python\common\listeners.py", line 42, in wrapper
    res = funct(*args)
  File "F:/Game\FreeOrion\default\python\AI\FreeOrionAI.py", line 348, in generateOrders
    action()
  File "F:/Game\FreeOrion\default\python\AI\FleetUtilsAI.py", line 594, in issue_fleet_orders_for_fleet_missions
    mission.issue_fleet_orders()
  File "F:/Game\FreeOrion\default\python\AI\AIFleetMission.py", line 547, in issue_fleet_orders
    if assertion_fails(new_fleet_id and new_fleet_id != INVALID_ID):
```

I will upload save file later on.

save: [92](https://github.com/jinlan/issue/blob/master/FreeOrion_Ego_Ego_0092_20210216_210951.7z)
Load the save and end turn.

**Comment by Cjkjvfnby** [comment]
I'll take a look at it in the next couple of days.

**Comment by Cjkjvfnby** [comment]
@jinlan, thank you for the report and the save-file.

I have checked, this is not an error, it's just a warning. This situation is handled in the code and it does not affect the AI behavior in a bad way.  Since this is a rare case I don't plan to investigate it further.  Feel free to reopen the issue if this warning will happen too often.

I have updated how the warning is reported to make it less confusing. https://github.com/freeorion/freeorion/pull/3320
