### ISSUE TITLE
AI client crash loading a saved game

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4059]
With current master, at least one of the AI clients crashes when I load the saved game attached to #4049.
```
Core was generated by `"/home/muzz/freeorion-project/myfo/freeorionca" AI_1 5 --resource.path "/home/m'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  (anonymous namespace)::TraceReference (property_name=..., ref_type=<optimized out>, context=...) at /home/muzz/freeorion-project/Grummel7/universe/UniverseObject.h:124
124	    [[nodiscard]] UniverseObjectType          ObjectType() const { return m_type; }
[Current thread is 1 (Thread 0x7fd453fdc700 (LWP 94012))]
(gdb) bt
#0  (anonymous namespace)::TraceReference (property_name=..., ref_type=<optimized out>, context=...) at /home/muzz/freeorion-project/Grummel7/universe/UniverseObject.h:124
#1  0x00007fd4582ce876 in ValueRef::Variable<int>::Eval (this=0x7fd4380f6230, context=...) at /home/muzz/freeorion-project/Grummel7/universe/ValueRefs.cpp:1035
#2  0x00007fd458145db4 in operator()<ValueRef::ValueRef<int>, ValueRef::ValueRef<int>, ValueRef::ValueRef<int> > (__closure=0x7fd453fdaf20, ref1=0x7fd4380f6090, ref2=0x7fd4380f6230, 
    ref3=0x0, context=...) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:9993
#3  0x00007fd458146e0d in Condition::ValueTest::Eval (this=0x7fd4380f5c90, parent_context=..., matches=std::vector of length 176, capacity 200 = {...}, non_matches=..., 
    search_domain=<optimized out>) at /usr/include/c++/10/bits/unique_ptr.h:173
#4  0x00007fd45813aad6 in Condition::And::Eval (this=0x7fd4380f5e60, parent_context=..., matches=std::vector of length 176, capacity 200 = {...}, 
    non_matches=std::vector of length 24, capacity 200 = {...}, search_domain=<optimized out>) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:10735
#5  0x00007fd458110c1b in Condition::Condition::Eval (this=0x7fd4380f5e60, parent_context=...) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:283
#6  0x00007fd45792b466 in ValueRef::Statistic<int, int>::Eval (this=0x7fd4380fe6b0, context=...) at /home/muzz/freeorion-project/Grummel7/parse/../universe/ValueRefs.h:1159
#7  0x00007fd458145b1e in operator()<ValueRef::ValueRef<int>, ValueRef::ValueRef<int>, ValueRef::ValueRef<int> > (__closure=0x7fd453fdb510, ref1=<optimized out>, ref2=0x7fd4380f6320, 
    ref3=<optimized out>, context=...) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:9912
#8  0x00007fd458146e0d in Condition::ValueTest::Eval (this=0x7fd4380f5d40, parent_context=..., matches=std::vector of length 14, capacity 50 = {...}, non_matches=..., 
    search_domain=<optimized out>) at /usr/include/c++/10/bits/unique_ptr.h:173
#9  0x00007fd45813adc9 in Condition::And::Eval (this=0x7fd4380fe410, parent_context=..., matches=std::vector of length 0, capacity 359, 
    non_matches=std::vector of length 36, capacity 50 = {...}, search_domain=<optimized out>) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:10710
#10 0x00007fd45813b1b6 in Condition::Or::Eval (this=<optimized out>, parent_context=..., matches=std::vector of length 0, capacity 359, 
    non_matches=std::vector of length 309, capacity 359 = {...}, search_domain=<optimized out>) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:10915
#11 0x00007fd45813aad6 in Condition::And::Eval (this=0x7fd4380fe560, parent_context=..., matches=std::vector of length 0, capacity 359, 
    non_matches=std::vector of length 309, capacity 359 = {...}, search_domain=<optimized out>) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:10735
#12 0x00007fd458110c1b in Condition::Condition::Eval (this=0x7fd4380fe560, parent_context=...) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:283
#13 0x00007fd45814547c in Condition::Condition::Eval (this=this@entry=0x7fd4380fe560, parent_context=...) at /home/muzz/freeorion-project/Grummel7/universe/Conditions.cpp:289
#14 0x00007fd458260096 in (anonymous namespace)::StoreTargetsAndCausesOfEffectsGroup<boost::container::flat_set<int> const> (context=..., effects_group=<optimized out>, source_objects=..., 
    effect_cause_type=<optimized out>, specific_cause_name=..., candidate_object_ids=..., candidate_objects_in=std::vector of length 0, capacity 0, 
    source_effects_targets_causes_out=std::vector of length 1, capacity 1 = {...}, n=740) at /home/muzz/freeorion-project/Grummel7/universe/Universe.cpp:1050
#15 0x00007fd4582609ec in operator() (this=0x7fd453fdbc10) at /home/muzz/freeorion-project/Grummel7/universe/Universe.cpp:1316
#16 boost::asio::asio_handler_invoke<(anonymous namespace)::DispatchEffectsGroupScopeEvaluations<std::deque<std::pair<std::vector<std::pair<Effect::SourcedEffectsGroup, Effect::TargetsAndCause> >, std::vector<std::pair<Effect::SourcedEffectsGroup, Effect::TargetsAndCause> >*> >, boost::container::flat_set<int> >::<lambda()> > (function=...)
    at /usr/include/boost/asio/handler_invoke_hook.hpp:88
#17 boost_asio_handler_invoke_helpers::invoke<(anonymous namespace)::DispatchEffectsGroupScopeEvaluations<std::deque<std::pair<std::vector<std::pair<Effect::SourcedEffectsGroup, Effect::TargetsAndCause> >, std::vector<std::pair<Effect::SourcedEffectsGroup, Effect::TargetsAndCause> >*> >, boost::container::flat_set<int> >::<lambda()>, (anonymous namespace)::DispatchEffectsGroupScopeEvaluations<std::deque<std::pair<std::vector<std::pair<Effect::SourcedEffectsGroup, Effect::TargetsAndCause> >, std::vector<std::pair<Effect::SourcedEffectsGroup, Effect::TargetsAndCause> >*> >, boost::container::flat_set<int> >::<lambda()> > (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:54
#18 boost::asio::detail::executor_op<(anonymous namespace)::DispatchEffectsGroupScopeEvaluations<std::deque<std::pair<std::vector<std::pair<Effect::SourcedEffectsGroup, Effect::TargetsAndCause> >, std::vector<std::pair<Effect::SourcedEffectsGroup, Effect::TargetsAndCause> >*> >, boost::container::flat_set<int> >::<lambda()>, std::allocator<void>, boost::asio::detail::scheduler_operation>::do_complete(void *, boost::asio::detail::scheduler_operation *, const boost::system::error_code &, std::size_t) (owner=<optimized out>, base=0x56136c95f520)
    at /usr/include/boost/asio/detail/executor_op.hpp:70
#19 0x000056136b92bcbf in boost::asio::detail::scheduler_operation::complete (bytes_transferred=0, ec=..., owner=0x56136c9011a0, this=0x56136c95f520)
    at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#20 boost::asio::detail::scheduler::do_run_one (this=0x56136c9011a0, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:481
#21 0x00007fd458257569 in boost::asio::detail::scheduler::run (this=0x56136c9011a0, ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:204
#22 0x00007fd458284498 in boost::asio::thread_pool::thread_function::operator() (this=<optimized out>) at /usr/include/boost/asio/impl/thread_pool.ipp:39
#23 boost::asio::detail::posix_thread::func<boost::asio::thread_pool::thread_function>::run (this=<optimized out>) at /usr/include/boost/asio/detail/posix_thread.hpp:86
#24 0x000056136b927070 in boost::asio::detail::boost_asio_detail_posix_thread_function (arg=0x56136cfdcdc0) at /usr/include/boost/asio/detail/impl/posix_thread.ipp:74
#25 0x00007fd457554ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#26 0x00007fd456b86def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

By recompiling various commits, I've narrowed it down, the problem seems to be introduced by 8b1d7c3dd9ee9b58d160980613a1a6caa5162eea

**Comment by geoffthemedio** [comment]
hopefully fixed by https://github.com/freeorion/freeorion/commit/2146e7280ed70f0e42a4ec06ba59ce2d66a0b557
