### ISSUE TITLE
Dismiss all sensor ghosts crashes the game

### ISSUE THREAD

**Issue by magnusviri** [freeorion/freeorion#4330]
Bug Report
==========

Clicking on "Dismiss all sensor ghosts crashes the game"

Environment
-----------

* [FreeOrion_2022-11-14.22c61c1_Test_MacOSX_10.12.dmg](https://sourceforge.net/projects/freeorion/files/FreeOrion/Test/FreeOrion_2022-11-14.22c61c1_Test_MacOSX_10.12.dmg/download)
* Mac OS X 12.6

Description
-----------

Clicking on "Dismiss all sensor ghosts here" crashes the game.

Expected Result
---------------

Sensor ghosts should go away.

Steps to reproduce
------------------

There's a Black Kraken sensor ghost at Stärn ß. Right-click on it and select "Dismiss All Sensor Ghosts Here" and it crashes.

[save-20221119_144011.sav.zip](https://github.com/freeorion/freeorion/files/10050857/save-20221119_144011.sav.zip)

**Comment by o01eg** [comment]
Backtrace without symbols: 

```
Thread 1 "freeorion" received signal SIGSEGV, Segmentation fault.
0x00007ffff78fba79 in Universe::ForgetKnownObject(int, int) () from /build-freeorion-rel/libfreeorioncommon.so
(gdb) bt
#0  0x00007ffff78fba79 in Universe::ForgetKnownObject(int, int) () from /build-freeorion-rel/libfreeorioncommon.so
#1  0x00007ffff7a231de in OrderSet::IssueOrder(std::shared_ptr<Order>, ScriptingContext&) () from /build-freeorion-rel/libfreeorioncommon.so
#2  0x0000555555a3451d in MapWnd::ForgetObject(int) ()
#3  0x0000555555a34767 in std::_Function_handler<void (), MapWnd::FleetButtonRightClicked(FleetButton const*)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#4  0x00007ffff6ba369f in GG::PopupMenu::Run() () from /build-freeorion-rel/libGiGi.so
#5  0x0000555555a16e1b in MapWnd::FleetButtonRightClicked(FleetButton const*) ()
#6  0x00007ffff6b097ee in boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() () from /build-freeorion-rel/libGiGi.so
#7  0x00007ffff6c015ec in GG::Wnd::HandleEvent(GG::WndEvent const&) () from /build-freeorion-rel/libGiGi.so
#8  0x00007ffff6b6002f in GG::GUIImpl::HandleMouseButtonRelease(unsigned int, GG::Pt, int) () from /build-freeorion-rel/libGiGi.so
#9  0x0000555555b6ec00 in SDLGUI::HandleSystemEvents() ()
#10 0x0000555555709cbd in GGHumanClientApp::HandleSystemEvents() ()
#11 0x00007ffff6b627d9 in GG::GUI::RunModal(std::shared_ptr<GG::Wnd>, bool&) () from /build-freeorion-rel/libGiGi.so
#12 0x0000555555b6decf in SDLGUI::Run() ()
#13 0x00005555556e07b4 in mainSetupAndRun() ()
#14 0x00005555556d7965 in main ()
```

Last lines in log:
```
22:00:02.200336 {0x00007ffff2a45cc0} [debug] FSM : HumanClientFSM.cpp:1287 : (PlayerFSM) PlayingGame::DispatchCombatLogs message received
22:00:02.207938 {0x00007ffff2a45cc0} [debug] timer : ScopedTimer.cpp:48 : GGHumanClientApp::UpdateCombatLogs time:     7461 µs
22:00:02.216808 {0x00007ffff2a45cc0} [debug] FSM : HumanClientFSM.cpp:1287 : (PlayerFSM) PlayingGame::DispatchCombatLogs message received
22:00:02.219710 {0x00007ffff2a45cc0} [debug] timer : ScopedTimer.cpp:48 : GGHumanClientApp::UpdateCombatLogs time:     2771 µs
22:00:05.229078 {0x00007ffff2a45cc0} [debug] client : Order.cpp:1895 : ForgetOrder::ExecuteImpl empire: 1 for object: 15434
```

**Comment by o01eg** [comment]
With symbols:

````
Thread 1 "freeorion" received signal SIGSEGV, Segmentation fault.
std::_Rb_tree<int, std::pair<int const, std::shared_ptr<UniverseObject> >, std::_Select1st<std::pair<int const, std::shared_ptr<UniverseObject> > >, std::less<int>, std::allocator<std::pair<int const, std::shared_ptr<UniverseObject> > > >::_M_lower_bound (__k=<synthetic pointer>: <optimized out>, __y=0x7fffffffd280, __x=0x25, this=0x7fffffffd278) at /usr/include/c++/12/bits/stl_tree.h:1952
1952		  __y = __x, __x = _S_left(__x);
(gdb) bt
#0  std::_Rb_tree<int, std::pair<int const, std::shared_ptr<UniverseObject> >, std::_Select1st<std::pair<int const, std::shared_ptr<UniverseObject> > >, std::less<int>, std::allocator<std::pair<int const, std::shared_ptr<UniverseObject> > > >::_M_lower_bound (__k=<synthetic pointer>: <optimized out>, __y=0x7fffffffd280, __x=0x25, this=0x7fffffffd278)
    at /usr/include/c++/12/bits/stl_tree.h:1952
#1  std::_Rb_tree<int, std::pair<int const, std::shared_ptr<UniverseObject> >, std::_Select1st<std::pair<int const, std::shared_ptr<UniverseObject> > >, std::less<int>, std::allocator<std::pair<int const, std::shared_ptr<UniverseObject> > > >::find (__k=<synthetic pointer>: <optimized out>, this=0x7fffffffd278) at /usr/include/c++/12/bits/stl_tree.h:2531
#2  std::map<int, std::shared_ptr<UniverseObject>, std::less<int>, std::allocator<std::pair<int const, std::shared_ptr<UniverseObject> > > >::find (
    __x=<synthetic pointer>: <optimized out>, this=0x7fffffffd278) at /usr/include/c++/12/bits/stl_map.h:1218
#3  ObjectMap::getRaw<UniverseObject> (this=0x7fffffffd278, id=15434) at /freeorion/universe/ObjectMap.h:433
#4  0x00007ffff78aa902 in Universe::ForgetKnownObject (this=0x7fffffffd218, empire_id=1, object_id=15434) at /freeorion/universe/Universe.cpp:1954
#5  0x00007ffff79c3d58 in OrderSet::IssueOrder (this=this@entry=0x7fffffffdbd0, order=std::shared_ptr<Order> (empty) = {...}, context=...)
    at /usr/include/c++/12/bits/shared_ptr_base.h:1665
#6  0x00005555559b1e15 in MapWnd::ForgetObject (this=0x555556121070, id=<optimized out>) at /freeorion/UI/MapWnd.cpp:4836
```
