### ISSUE TITLE
AI errors on turn of reload

### ISSUE THREAD

**Issue by MichaelCourtney** [freeorion/freeorion#4566]
Bug Report
==========

build 2023-06-19.aa45874

How to produce:

Start a game, turn a few times, exit to menu, select continue. Hit turn. Errors on 1st turn after reload.

**Comment by geoffthemedio** [comment]
````
[21 Jun 23:07:36] AI_5: AI_Error: AI script error : FreeOrionAI.py:prepareForSave():226  - Failed to encode the AIstate as save-state string. The resulting save file should be playable but the AI may have a different aggression. The error raised was: 'ShipCombatStats' object has no attribute '_structure'
Traceback (most recent call last):
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 69, in encode
    encoder = _encoder_table[o_type]
KeyError: <class 'AIstate.AIstate'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 69, in encode
    encoder = _encoder_table[o_type]
KeyError: <class 'CombatRatingsAI._ship_combat_stats.ShipCombatStats'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\FreeOrionAI.py", line 223, in prepareForSave
    dump_string = savegame_codec.build_savegame_string()
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 54, in build_savegame_string
    savegame_string = encode(get_aistate())
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 75, in encode
    return _encode_object(o)
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 130, in _encode_object
    return _encode_dict(value)
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 150, in _encode_dict
    return "{%s}" % (", ".join([f"{encode(k)}: {encode(v)}" for k, v in o.items()]))
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 150, in <listcomp>
    return "{%s}" % (", ".join([f"{encode(k)}: {encode(v)}" for k, v in o.items()]))
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 75, in encode
    return _encode_object(o)
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\savegame_codec\_encoder.py", line 126, in _encode_object
    value = getstate()
  File "C:\Users\g_top\Desktop\FOSDK14\FreeOrion\default\python\AI\CombatRatingsAI\_ship_combat_stats.py", line 46, in __getstate__
    "structure": self._structure,
AttributeError: 'ShipCombatStats' object has no attribute '_structure'
Local context: {'self': <CombatRatingsAI._ship_combat_stats.ShipCombatStats object at 0x00000000056F19D0>}
````
