### ISSUE TITLE
[AI] Some bindings are broken

### ISSUE THREAD

**Issue by Cjkjvfnby** [freeorion/freeorion#4580]
Bug Report
==========

Description
-----------
Error that calling some AI binding manually.  (AI does not use this code)
```
26 Jun 22:25:38] AI_1: Uncaught exception: Traceback (most recent call last):
  File "J:\games\FreeOrion\python39.zip\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: No Python class registered for C++ class class std::map<class boost::container::flat_set<int,struct std::less<int>,void>,float,struct std::less<class boost::container::flat_set<int,struct std::less<int>,void> >,class std::allocator<struct std::pair<class boost::container::flat_set<int,struct std::less<int>,void> const ,float> > >
```

Expected Result
---------------
Value is returned or function is not exposed to AI

Steps to reproduce
------------------
- Start game with debug chat
- Debug any empire `start 2`
- Input: `e.productionQueue.allocatedPP`

**Comment by geoffthemedio** [comment]
try with https://github.com/freeorion/freeorion/commit/1b65ab80b86cf999d13f8d5eed10151dbcfa1b94
