### ISSUE TITLE
Universe generation fails on macOS

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#4644]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 4f3c4ba8de5fa8e5616bf7f8a554d5d661a31617
* **Operating System**: macOS 12.6
* **Graphic card used**: Intel Iris Plus Graphics 655
* **Fetched as** 
  * Compiled from source

Description
-----------

After starting a game universe generation reports errors, no universe gets created.

Log files:
[logfiles.zip](https://github.com/freeorion/freeorion/files/12160859/logfiles.zip)

Expected Result
---------------

Universe generation succeeds.

Steps to reproduce
------------------

Start new game.

**Comment by Vezzra** [comment]
Narrowed down the range of commits where the issue has been introduced:

Last working weekly test build: 2023-06-19.aa45874
First weekly test builds with described issue: 2023-06-27.1b21f9b

**Comment by hifron** [comment]
Is SDK with XCode built agains MacOS 11? Because current master is not on 11 anymore...

**Comment by o01eg** [comment]
@hifron Was it changed between aa45874 and 1b21f9b?

@Vezzra Could you use bisect to found commit which broke it.

**Comment by hifron** [comment]
@o01eg  No. In https://github.com/freeorion/freeorion/pull/4635/ . But MacOS could have updates with XCode and its dependencies raised... According [MacOS 12](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md) required XCode is 13.1

**Comment by geoffthemedio** [comment]
In the log:
````
13:04:54.706946 {0x0000000111268600} [error] server : PythonCommon.cpp:101 : Traceback (most recent call last):
13:04:54.706987 {0x0000000111268600} [error] server : PythonCommon.cpp:101 :   File "/Volumes/FreeOrion/FreeOrion.app/Contents/Resources/default/python/universe_generation/starsystems.py", line 39, in pick_star_type
    + universe_tables.UNIVERSE_AGE_MOD_TO_STAR_TYPE_DIST[galaxy_age][candidate]
13:04:54.707007 {0x0000000111268600} [error] server : PythonCommon.cpp:101 : KeyError: freeorion.galaxySetupOptionGeneric.none
13:04:54.707022 {0x0000000111268600} [error] server : PythonCommon.cpp:101 : 
During handling of the above exception, another exception occurred:
13:04:54.707038 {0x0000000111268600} [error] server : PythonCommon.cpp:101 : Traceback (most recent call last):
13:04:54.707053 {0x0000000111268600} [error] server : PythonCommon.cpp:101 :   File "/Volumes/FreeOrion/FreeOrion.app/Contents/Resources/default/python/common/listeners.py", line 42, in wrapper
    res = funct(*args)
13:04:54.707068 {0x0000000111268600} [error] server : PythonCommon.cpp:101 :   File "/Volumes/FreeOrion/FreeOrion.app/Contents/Resources/default/python/universe_generation/universe_generator.py", line 106, in create_universe
    systems = generate_systems(system_positions, gsd)
13:04:54.707084 {0x0000000111268600} [error] server : PythonCommon.cpp:101 :   File "/Volumes/FreeOrion/FreeOrion.app/Contents/Resources/default/python/universe_generation/starsystems.py", line 91, in generate_systems
    star_type = pick_star_type(gsd.age)
13:04:54.707099 {0x0000000111268600} [error] server : PythonCommon.cpp:101 :   File "/Volumes/FreeOrion/FreeOrion.app/Contents/Resources/default/python/universe_generation/starsystems.py", line 48, in pick_star_type
    util.report_error("Python pick_star_type: Pick star type failed\n" + sys.exc_info()[1])
13:04:54.707113 {0x0000000111268600} [error] server : PythonCommon.cpp:101 : TypeError: can only concatenate str (not "KeyError") to str
````

Indeed, there is no entry for `none` option in the table: https://github.com/freeorion/freeorion/blob/master/default/python/universe_generation/universe_tables.py#L36-L44

Possibly it's looking for the `none` due to some earlier case errors in the log:
````
13:04:51.027191 {0x0000000111268600} [error] server : OptionsDB.h:150 : bad any cast converting value option named: setup.galaxy.shape. Returning default value instead
13:04:51.027213 {0x0000000111268600} [error] server : OptionsDB.h:154 : bad any cast converting default value of option named: setup.galaxy.shape. Returning data-type default value instead: SPIRAL_2
13:04:51.027235 {0x0000000111268600} [error] server : OptionsDB.h:150 : bad any cast converting value option named: setup.galaxy.age. Returning default value instead
13:04:51.027252 {0x0000000111268600} [error] server : OptionsDB.h:154 : bad any cast converting default value of option named: setup.galaxy.age. Returning data-type default value instead: GALAXY_SETUP_NONE
13:04:51.027273 {0x0000000111268600} [error] server : OptionsDB.h:150 : bad any cast converting value option named: setup.starlane.frequency. Returning default value instead
13:04:51.027291 {0x0000000111268600} [error] server : OptionsDB.h:154 : bad any cast converting default value of option named: setup.starlane.frequency. Returning data-type default value instead: GALAXY_SETUP_NONE
13:04:51.027308 {0x0000000111268600} [error] server : OptionsDB.h:150 : bad any cast converting value option named: setup.planet.density. Returning default value instead
13:04:51.027325 {0x0000000111268600} [error] server : OptionsDB.h:154 : bad any cast converting default value of option named: setup.planet.density. Returning data-type default value instead: GALAXY_SETUP_NONE
13:04:51.027342 {0x0000000111268600} [error] server : OptionsDB.h:150 : bad any cast converting value option named: setup.specials.frequency. Returning default value instead
13:04:51.027359 {0x0000000111268600} [error] server : OptionsDB.h:154 : bad any cast converting default value of option named: setup.specials.frequency. Returning data-type default value instead: GALAXY_SETUP_NONE
13:04:51.027377 {0x0000000111268600} [error] server : OptionsDB.h:150 : bad any cast converting value option named: setup.monster.frequency. Returning default value instead
13:04:51.027394 {0x0000000111268600} [error] server : OptionsDB.h:154 : bad any cast converting default value of option named: setup.monster.frequency. Returning data-type default value instead: MONSTER_SETUP_NONE
13:04:51.027425 {0x0000000111268600} [error] server : OptionsDB.h:150 : bad any cast converting value option named: setup.native.frequency. Returning default value instead
13:04:51.027444 {0x0000000111268600} [error] server : OptionsDB.h:154 : bad any cast converting default value of option named: setup.native.frequency. Returning data-type default value instead: GALAXY_SETUP_NONE
13:04:51.027461 {0x0000000111268600} [error] server : OptionsDB.h:150 : bad any cast converting value option named: setup.ai.aggression. Returning default value instead
13:04:51.027479 {0x0000000111268600} [error] server : OptionsDB.h:154 : bad any cast converting default value of option named: setup.ai.aggression. Returning data-type default value instead: BEGINNER
````

@Vezzra Possibly related to replacing `boost::any` with `std::any` in https://github.com/freeorion/freeorion/commit/d69f91ab518fabdf89a0315597eb1e6fb73f6a67 ... You could try before/after that commit?

**Comment by Vezzra** [comment]
Yes, commit d69f91ab518fabdf89a0315597eb1e6fb73f6a67 is the culprit, introduced the issue.

**Comment by geoffthemedio** [comment]
reverting the changes of d69f91ab518fabdf89a0315597eb1e6fb73f6a67 on the latest master seemingly works for me, can you try it also?

**Comment by Vezzra** [comment]
Yes, reverting d69f91ab518fabdf89a0315597eb1e6fb73f6a67 works and fixes the issue on Mac.
