### ISSUE TITLE
Client crash clicking on a system as moderator

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4664]
Today I tried to have a look at #4661. I synchronised to master (8c1579a7d388fb8016493fd6c81bbae7e8960f3a) and merged the AI changes.

As usual for testing AI behaviour, I started a multiplayer game with me as moderator.
But as soon as I click on a system, the client crashes reproducible.

Stack trace:
```
#0  0x00007f0bb877180f in Empire::Source (this=this@entry=0x0, objects=...) at Empire/Empire.cpp:95
#1  0x0000556cddf9bec8 in SidePanel::PlanetPanel::Refresh (this=0x556ce30ee0f0, context=...)
    at UI/SidePanel.cpp:1657
#2  0x0000556cddfa2777 in SidePanel::PlanetPanel::CompleteConstruction (this=<optimized out>)
    at UI/SidePanel.cpp:1119
#3  0x0000556cddfa3ff7 in GG::Wnd::Create<SidePanel::PlanetPanel, GG::X, int&, StarType&> ()
    at GG/GG/Wnd.h:325
#4  SidePanel::PlanetPanelContainer::SetPlanets (this=0x556ce1d08f10, planet_ids=..., star_type=StarType::STAR_ORANGE, context=...)
    at UI/SidePanel.cpp:2803
#5  0x0000556cddfa4c5a in SidePanel::RefreshImpl (this=0x556ce1bc85d0, context=...)
    at UI/../universe/System.h:68
#6  0x0000556cddfa597c in SidePanel::RefreshInPreRender (this=<optimized out>, context=...)
    at UI/SidePanel.cpp:3389
#7  0x0000556cddfa6743 in SidePanel::PreRender (this=0x556ce1bc85d0) at UI/SidePanel.cpp:3326
#8  0x00007f0bb7db4bab in GG::GUI::PreRender (this=0x7fffe3916d08) at /usr/include/c++/10/bits/shared_ptr_base.h:1324
#9  0x00007f0bb7dbc63f in GG::GUI::RunModal (this=this@entry=0x7fffe3916d08, done=@0x7fffe3916dba: false)
    at GG/src/GUI.cpp:1280
#10 0x0000556cddf7cd4c in SDLGUI::Run (this=0x7fffe3916d08) at UI/SDLGUI.cpp:524
#11 0x0000556cddb4f093 in mainSetupAndRun () at client/human/chmain.cpp:303
#12 0x0000556cddb4551b in main (argc=<optimized out>, argv=<optimized out>)
    at client/human/chmain.cpp:102
```

**Comment by geoffthemedio** [comment]
Hopefully fixed by #4665
