### ISSUE TITLE
Game crashes when enter to multiplayer window with cookies saved

### ISSUE THREAD

**Issue by o01eg** [freeorion/freeorion#4741]
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2023-09-05.8b4e2e8
* **Operating System**: Linux
* **Graphic card used**: Intel
* **Fetched as** 
  * Compiled from source

Description
-----------

backtrace:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  OptionsDB::Get<>() : Attempted to get nonexistent option "M��

Thread 1 "freeorion" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: Нет такого файла или каталога.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff56a815f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff565a472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff56444b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff58a09db in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff58affaa in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff58b0015 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff58b0268 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00005555556b4852 in OptionsDB::Get<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (this=<optimized out>, name=...)
    at /usr/include/c++/13/bits/allocator.h:184
#9  0x0000555555ae4e79 in ServerConnectWnd::PopulateServerList (this=this@entry=0x5555566395c0) at /home/oleg/devel/freeorion/UI/ServerConnectWnd.cpp:205
#10 0x0000555555ae7072 in ServerConnectWnd::CompleteConstruction (this=<optimized out>) at /home/oleg/devel/freeorion/UI/ServerConnectWnd.cpp:158
#11 0x00005555556dc359 in GG::Wnd::Create<ServerConnectWnd> () at /home/oleg/devel/freeorion/GG/GG/Wnd.h:325
#12 0x00005555556d231c in GGHumanClientApp::MultiPlayerGame (this=0x7fffffffd0a0) at /home/oleg/devel/freeorion/client/human/GGHumanClientApp.cpp:634
#13 0x00007ffff6b03b70 in boost::function0<void>::operator() (this=<optimized out>) at /usr/include/boost/function/function_template.hpp:763
#14 boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke<boost::function<void ()> >(boost::function<void ()>&, boost::signals2::detail::unsigned_meta_array<>, std::tuple<> const&, boost::enable_if<boost::is_void<boost::function<void ()>::result_type>, void>::type*) const (func=..., this=<optimized out>)
    at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:117
#15 boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()<boost::function<void ()>, , 0ul>(boost::function<void ()>&, std::tuple<> const&, mpl_::size_t<0ul>) const (args=empty std::tuple, func=..., this=<optimized out>) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#16 boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > const&) const (
    connectionBody=..., this=0x7fffffffca00) at /usr/include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#17 boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >::dereference() const (this=0x7fffffffc830) at /usr/include/boost/signals2/detail/slot_call_iterator.hpp:110
#18 boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > const&) (f=...) at /usr/include/boost/iterator/iterator_facade.hpp:550
#19 boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<void (), boost::function<void ()> >, boost::signals2::mutex> >, boost::signals2::detail::void_type, boost::iterators::single_pass_traversal_tag, boost::signals2::detail::void_type const&, long, false, false>::operator*() const (this=0x7fffffffc830) at /usr/include/boost/iterator/iterator_facade.hpp:656
```

Expected Result
---------------

Servers window appears with saved servers.

Steps to reproduce
------------------

* Log in on multiplayer server.
* Leave it.
* Close client
* Try to press multiplayer button.

**Comment by geoffthemedio** [comment]
Can you set a server password and pm it to me in the forum? I guess you disabled the one time passwords, since I'm not getting emails like before after trying to connect...

Probly not necessary for this issue, though, so no rush.

Edit: OTPs showed up this morning, with timestamps for sent yesterday evening...
