### ISSUE TITLE
Python typing error

### ISSUE THREAD

**Issue by geoffthemedio** [freeorion/freeorion#4844]
In latest master (d598700d) but not (0414d6be) with SDK14, running freeorion outputs to the console:
````
C:\Users\g_top\Desktop\FOSDK14\FreeOrionL>FreeOrion.exe
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'typing'
````

And in freeorion.log:
````
10:45:31.391558 {0x00008518} [error] client : PythonParser.cpp:400 : Couldn't find file for module spec typing
10:45:31.392559 {0x00008518} [error] client : PythonCommon.cpp:91 : Missing python exception type
10:45:31.392559 {0x00008518} [error] client : PythonParser.cpp:448 : Unable to parse module file C:/Users/g_top/Desktop/FOSDK14/FreeOrionL/default\scripting\focs\_types.py
````

**Comment by Cjkjvfnby** [comment]
This error comes from the helper for the typing, this file should not be executed during script parsing.  

I'd recommend one of:
- exclude files started from underscore,
- exclude `j:/projects/freeorion/default\scripting\focs` from parsing

```
23:45:20.137230 {0x0000109c} [debug] ai : PythonParser.cpp:434 : Executing module file j:/projects/freeorion/default\scripting\focs\_types.py
23:45:20.138230 {0x0000109c} [error] ai : PythonParser.cpp:400 : Couldn't find file for module spec typing
```

**Comment by o01eg** [comment]
@Cjkjvfnby Can we use execution context to conditionally import those files?

**Comment by Cjkjvfnby** [comment]
> Can we use execution context to conditionally import those files?

Not sure what you mean.  

This file should not be imported during FOCS parsing.  It's imported inside the pyi file that is never executed (static type checker is using it).

I'll check if I can move it somewhere.

**Comment by o01eg** [comment]
Can we write something like:

```python
if not ParserContext:
    from focs._species import *
```

I can define builtins in parser if needed.

**Comment by Cjkjvfnby** [comment]
Actually I'd prefer to include `typing` module in Python on Windows.   It would be nice to use it in macros.

**Comment by geoffthemedio** [comment]
Still getting errors similar to this in master:
````
01:06:52.446006 {0x00008494} [debug] server : PythonParser.cpp:434 : Executing module file C:/Users/g_top/Desktop/FOSDK14/FreeOrionAlt/default\scripting\focs\_types.py
01:06:52.446006 {0x00008494} [error] server : PythonParser.cpp:400 : Couldn't find file for module spec typing
01:06:52.447007 {0x00008494} [error] server : PythonCommon.cpp:102 : Traceback (most recent call last):
01:06:52.447007 {0x00008494} [error] server : PythonCommon.cpp:102 :   File "<string>", line 3, in <module>
01:06:52.447007 {0x00008494} [error] server : PythonCommon.cpp:102 : ModuleNotFoundError: No module named 'typing'
01:06:52.447007 {0x00008494} [error] server : PythonParser.cpp:448 : Unable to parse module file C:/Users/g_top/Desktop/FOSDK14/FreeOrionAlt/default\scripting\focs\_types.py
````

**Comment by geoffthemedio** [comment]
@o01eg @Cjkjvfnby any updates about this?

**Comment by geoffthemedio** [comment]
Still get:
````
09:47:26.930753 {0x00006fd0} [debug] client : PythonParser.cpp:434 : Executing module file C:/Users/g_top/Desktop/FOSDK14/FreeOrionAlt/default\scripting\focs\_types.py
09:47:26.931753 {0x00006fd0} [error] client : PythonParser.cpp:400 : Couldn't find file for module spec typing
09:47:26.931753 {0x00006fd0} [error] client : PythonParser.cpp:400 : Couldn't find file for module spec focs._types._EffectGroup
````

**Comment by o01eg** [comment]
@geoffthemedio Maybe make parser more strict so such errors will cause tests to fail?

**Comment by geoffthemedio** [comment]
If that makes sense to you, I have no objection...
