### ISSUE TITLE
AI can not process ship parts with Core and another slottype

### ISSUE THREAD

**Issue by dbenage-cx** [freeorion/freeorion#582]
Setting `mountableSlotTypes = [Internal Core]` for a ship part outputs the following in each of the AI logs each turn:

```
2016-04-02 23:32:48.041204 [debug] AI : -----   Updating ShipDesign cache for new turn   -----
2016-04-02 23:32:48.041241 [debug] AI : Checking persistent cache for consistency...
2016-04-02 23:32:48.042800 [debug] AI : Updating Testdesigns for hulls...
2016-04-02 23:32:48.042855 [debug] AI : Caching buildable hulls per planet...
2016-04-02 23:32:48.043124 [debug] AI : Updating test designs for ship parts...
2016-04-02 23:32:48.043231 [debug] AI : Caching buildable ship parts per planet...
2016-04-02 23:32:48.043557 [debug] AI : possible recipients host status: [(1, True), (2, False), (3, False)]
2016-04-02 23:32:48.043840 [debug] AI : 
2016-04-02 23:32:48.043873 [debug] AI : Chat Message to human: AI_Error: AI script error in "find_best_designs_this_turn": "freeOrionAIInterface.shipSlotType.core"
2016-04-02 23:32:48.043903 [debug] AI : 
2016-04-02 23:32:48.044086 [error] AI : Traceback (most recent call last):
2016-04-02 23:32:48.044116 [error] AI :   File "/opt/projects/freeorion/default/AI/FreeOrionAI.py", line 248, in generateOrders
2016-04-02 23:32:48.044138 [error] AI :     action()
2016-04-02 23:32:48.044156 [error] AI :   File "/opt/projects/freeorion/default/AI/ProductionAI.py", line 45, in find_best_designs_this_turn
2016-04-02 23:32:48.044175 [error] AI :     ShipDesignAI.Cache.update_for_new_turn()
2016-04-02 23:32:48.044194 [error] AI :   File "/opt/projects/freeorion/default/AI/ShipDesignAI.py", line 139, in update_for_new_turn
2016-04-02 23:32:48.044212 [error] AI :     self._update_buildable_items_this_turn(verbose=False)
2016-04-02 23:32:48.044232 [error] AI :   File "/opt/projects/freeorion/default/AI/ShipDesignAI.py", line 570, in _update_buildable_items_this_turn
2016-04-02 23:32:48.044249 [error] AI :     local_cache[slot].append(partname)
2016-04-02 23:32:48.044267 [error] AI : KeyError: freeOrionAIInterface.shipSlotType.core
2016-04-02 23:32:48.044305 [debug] AI : checking statuses
```

Same results for `mountableSlotTypes = [External Core]`

**Comment by Cjkjvfnby** [comment]
Can you specify which part exactly?

**Comment by dbenage-cx** [comment]
changing `SR_WEAPON_1_1` to `[External Core]` will reproduce

There are currently no ship parts in master that use either combination.

Edit: it may be needed for issue #541
